### ISSUE TITLE
Cant read banner_base - did you export Textures first?

### ISSUE THREAD

**Issue by phoenixlzx** [jmc2obj/j-mc-2-obj#103]
I got this error when exporting obj:

```
Banner ***************************
Cant read banner_base - did you export Textures first?
javax.imageio.IIOException: Can't read input file!
    at javax.imageio.ImageIO.read(ImageIO.java:1301)
    at org.jmc.models.Banner.generateBannerImage(Unknown Source)
    at org.jmc.models.Banner.addModel(Unknown Source)
    at org.jmc.OBJOutputFile.addChunkBuffer(Unknown Source)
    at org.jmc.ObjExporter.export(Unknown Source)
    at org.jmc.gui.ExportWindow$9$1$1.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

It keeps prompting and the file exported could not be used.

**Comment by mmdanggg2** [comment]
"did you export Textures first?"

**Comment by phoenixlzx** [comment]
Actually I do exported textures from Minecraft, but the error still comes out.

Maybe problems with map file.

**Comment by mmdanggg2** [comment]
Doubt it, the error is saying that it cannot find the banner texture. This shouldn't stop the exported OBJ from being usable though. Try exporting textures with alpha channel in separate files.

**Comment by phoenixlzx** [comment]
* export alpha channel in seperate files checked
* export all textures in a single file unchecked

`banner_base.png` exists in exported directory, but the error persists.

**Comment by phoenixlzx** [comment]
Well I deselected those two banner blocks in 'blocks to export' and successed. :/

**Comment by mmdanggg2** [comment]
hmm, It should have been fine even with that error. Just that the banner texture wouldn't have been created.

**Comment by phoenixlzx** [comment]
Tried with leave that error which keeping jumping out and after several seconds the program freezed.

I will do some more tests with my co-worker tomorrow.
