### ISSUE TITLE
Headless mode?

### ISSUE THREAD

**Issue by RobertHerhold** [jmc2obj/j-mc-2-obj#106]
Hi, awesome project!

I'm looking at using this for one of my projects, but it would require that I be able to do this without the UI... my world would contain *only* the blocks I want to export and the default settings would be fine. Is there any way to do this currently, and if not, would it be a possible addition?

**Comment by mmdanggg2** [comment]
There is a command line mode, I haven't tried it myself but you can get a list of options with this command "java -jar jmc2obj.jar --help"

**Comment by paol** [comment]
Yes, the command line mode will do what you need.

If you need help you can ask questions in the [reddig group](https://www.reddit.com/r/jmc2obj/)
