### ISSUE TITLE
Blender Cycles Material Script - Needs an update!

### ISSUE THREAD

**Issue by MarcusCemes** [jmc2obj/j-mc-2-obj#108]
The script contribution for creating all cycle node materials for each block is incredibly useful but is now broken. I don't understand why it worked before, but it did.

**Bug 1:**

![image](https://cloud.githubusercontent.com/assets/20288819/26117764/d67df27e-3a67-11e7-86e6-60cff614198d.png)
Windows paths use a \ instead of an / , the script checks for exact string equality. Lines 113 and 114 need to be modified to
```
checkPath = '//tex\\' + texName + '.png'
checkPathAlpha = '//tex\\' + texName + '_a.png'
```
instead of
```
checkPath = '//tex/' + texName + '.png'
checkPathAlpha = '//tex/' + texName + '_a.png'
```
As this only seems to be an issue with Windows, a better source checker is needed, perhaps that only checks the texName? Or a dirty fix would be to check both possible checkPaths

**Bug 2:**

![image](https://cloud.githubusercontent.com/assets/20288819/26117942/70c45242-3a68-11e7-9073-168ac4e40c3d.png)
The glass material fails when an alpha image is not present. (line 297)
Needs to check the availability of an alpha image.

I don't have the python or blender knowledge to offer a contribution, if anyone could spare the time it would be greatly appreciated, especially considering how Cycles is becoming more and more popular, and jmc2obj is the only tool I've found capable of automating Cycles materials (with the help of this script)

**Comment by danijel3** [comment]
That script is pretty outdated.

Have you tried using the "Materials Utils Specials" addon that comes preisntalled with every Blender installation? Just go to user preferences, use the search to find it and activate it. Once you do that, you should have a "Convert BI Materials to Cycles" in your materials tab.

Let me know here if this method works.

**Comment by MarcusCemes** [comment]
A beautiful and very elegant solution. The "Convert BI Materials to Cycles" option did nothing for me, but the "Convert to BI and Cycles Nodes" created a beautiful default node setup that seems to work just as well.

It does require some tweaks that the script did automatically, such as emission or glass materials, but the advantage is support for alpha channels in the same image, as jmc2obj doesn't seem to export alpha images even when it's enabled...

Thanks for calling this out, you've just saved me loads of time!

**Comment by danijel3** [comment]
Thanks for testing it out. Haven't had the opportunity to try it out myself. I'll save this issue as a reply for others who run into the same problem...
