### ISSUE TITLE
Disabled 'Load' Button on Linux.

### ISSUE THREAD

**Issue by RichardOjo** [jmc2obj/j-mc-2-obj#109]
Every time i launch jmc2obj it says 'couldn't load default.mtl' or anything else like that. Is it affecting the load button because every time i located the saves folder and clicked on the world it still disabled. Can you help?

OS: Linux Mint 17.3 (Ubuntu Type: Trusty)
Thank You.

**Comment by danijel3** [comment]
When you first launched the application, was a folder named "conf" created in the same folder as the JAR file?

Can you copy the log from the terminal here?

**Comment by RichardOjo** [comment]
I just moved the config folder next to the jar file and it worked perfectly. Thank you. Luckily I did not need to show you the log.

**Comment by danijel3** [comment]
Okay. No probs...
