### ISSUE TITLE
How to join a new language?

### ISSUE THREAD

**Issue by wsndshx** [jmc2obj/j-mc-2-obj#110]
I have completed a language resource kit, but I do not know how to add to the program.

**Comment by danijel3** [comment]
It has to be added to the project. You can either create a pull request on github (as per [these](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) instructions) or just send them to me and I'll add it for you (you can put them on some file sharing site and post a link here).

**Comment by wsndshx** [comment]
OK, I have already submitted the pull request.

**Comment by danijel3** [comment]
Just updated the project and uploaded it on the server. You can update your program and see if it looks okay now.

Thanks for the contribution! Do you want credit in the app about box?

**Comment by wsndshx** [comment]
Oh, sorry. Because I went back to school, I did not reply in time.

**Comment by wsndshx** [comment]
If so then of course great.Name to use "zzlwd"?
