### ISSUE TITLE
jMC2Obj Load Button Grayed Out!

### ISSUE THREAD

**Issue by Beebleblox** [jmc2obj/j-mc-2-obj#113]
I select a world file and I cannon click the load button because, you know why. Am I using the wrong kind of 
world file or what?
![screenshot from 2018-07-17 00-48-17](https://user-images.githubusercontent.com/41293676/42759460-2c39c358-895b-11e8-8d67-9c699dee297c.png)

**Comment by danijel3** [comment]
Can you click on the "Open Console" button? Does it say anything useful there?

**Comment by Beebleblox** [comment]
When I open it up it says "Error reading configuration file." Then it says 
java.lang.Exception: Cannot open configuration file conf/defult.mtl 
           at org.jmc.Materials.readConfig(Unknown Source) 
           at org.jmc.Materials.initialize(Unknown Source) 
           at org.jmc.Main.runGUI(Unknown Source)
           at org.jmc.Main.main(Unknown Source)

Error: Cannot check update

That was the Console, the Error Message says "Cannot check update, SAXParseException: White spaces are required between PublicID and SystemID."

I'm using Linux Mint 18.3 by the way, would that be a problem?

**Comment by Beebleblox** [comment]
Ps. it also says this: WARNING: cannot find the hash file! I will create backups of any existing configuration files.
You can delete them if you didn't make any changes to them.
File conf/Updater.jar is modified! I will create a backup to /home/beebleblox/conf/Updater.jar.bak and recreate the new file.
File conf/blocks.conf is modified! I will create a backup to /home/beebleblox/conf/blocks.conf.bak and recreate the new file.
File conf/contrib/BLENDER_cycles.py is modified! I will create a backup to /home/beebleblox/conf/contrib/BLENDER_cycles.py.bak and recreate the new file.
File conf/contrib/MAYA_readme.txt is modified! I will create a backup to /home/beebleblox/conf/contrib/MAYA_readme.txt.bak and recreate the new file.
File conf/default.mtl is modified! I will create a backup to /home/beebleblox/conf/default.mtl.bak and recreate the new file.
File conf/entities.conf is modified! I will create a backup to /home/beebleblox/conf/entities.conf.bak and recreate the new file.
File conf/license.txt is modified! I will create a backup to /home/beebleblox/conf/license.txt.bak and recreate the new file.
File conf/models/anvil.obj is modified! I will create a backup to /home/beebleblox/conf/models/anvil.obj.bak and recreate the new file.
File conf/models/armor_chest.obj is modified! I will create a backup to /home/beebleblox/conf/models/armor_chest.obj.bak and recreate the new file.
File conf/models/armor_feet.obj is modified! I will create a backup to /home/beebleblox/conf/models/armor_feet.obj.bak and recreate the new file.
File conf/models/armor_helmet.obj is modified! I will create a backup to /home/beebleblox/conf/models/armor_helmet.obj.bak and recreate the new file.
File conf/models/armor_legs.obj is modified! I will create a backup to /home/beebleblox/conf/models/armor_legs.obj.bak and recreate the new file.
File conf/models/armor_stand.obj is modified! I will create a backup to /home/beebleblox/conf/models/armor_stand.obj.bak and recreate the new file.
File conf/models/banner_standing.obj is modified! I will create a backup to /home/beebleblox/conf/models/banner_standing.obj.bak and recreate the new file.
File conf/models/banner_wall.obj is modified! I will create a backup to /home/beebleblox/conf/models/banner_wall.obj.bak and recreate the new file.
File conf/models/beacon.obj is modified! I will create a backup to /home/beebleblox/conf/models/beacon.obj.bak and recreate the new file.
File conf/models/brewing_stand.obj is modified! I will create a backup to /home/beebleblox/conf/models/brewing_stand.obj.bak and recreate the new file.
File conf/models/cake.obj is modified! I will create a backup to /home/beebleblox/conf/models/cake.obj.bak and recreate the new file.
File conf/models/cauldron.obj is modified! I will create a backup to /home/beebleblox/conf/models/cauldron.obj.bak and recreate the new file.
File conf/models/chicken.obj is modified! I will create a backup to /home/beebleblox/conf/models/chicken.obj.bak and recreate the new file.
File conf/models/cow.obj is modified! I will create a backup to /home/beebleblox/conf/models/cow.obj.bak and recreate the new file.
File conf/models/enchant_table.obj is modified! I will create a backup to /home/beebleblox/conf/models/enchant_table.obj.bak and recreate the new file.
File conf/models/enderdragon_egg.obj is modified! I will create a backup to /home/beebleblox/conf/models/enderdragon_egg.obj.bak and recreate the new file.
File conf/models/endportal_frame.obj is modified! I will create a backup to /home/beebleblox/conf/models/endportal_frame.obj.bak and recreate the new file.
File conf/models/entities.obj is modified! I will create a backup to /home/beebleblox/conf/models/entities.obj.bak and recreate the new file.
File conf/models/flowerpot.obj is modified! I will create a backup to /home/beebleblox/conf/models/flowerpot.obj.bak and recreate the new file.
File conf/models/hopper.obj is modified! I will create a backup to /home/beebleblox/conf/models/hopper.obj.bak and recreate the new file.
File conf/models/pig.obj is modified! I will create a backup to /home/beebleblox/conf/models/pig.obj.bak and recreate the new file.
File conf/models/sheep.obj is modified! I will create a backup to /home/beebleblox/conf/models/sheep.obj.bak and recreate the new file.
File conf/models/squid.obj is modified! I will create a backup to /home/beebleblox/conf/models/squid.obj.bak and recreate the new file.
File conf/single.mtl is modified! I will create a backup to /home/beebleblox/conf/single.mtl.bak and recreate the new file.
File conf/singletex.mtl is modified! I will create a backup to /home/beebleblox/conf/singletex.mtl.bak and recreate the new file.
File conf/texsplit_1.5.conf is modified! I will create a backup to /home/beebleblox/conf/texsplit_1.5.conf.bak and recreate the new file.
File conf/texsplit_1.6.conf is modified! I will create a backup to /home/beebleblox/conf/texsplit_1.6.conf.bak and recreate the new file.
File conf/texsplit_old.conf is modified! I will create a backup to /home/beebleblox/conf/texsplit_old.conf.bak and recreate the new file.
File conf/textures/endportal.png is modified! I will create a backup to /home/beebleblox/conf/textures/endportal.png.bak and recreate the new file.
File conf/textures/fire.png is modified! I will create a backup to /home/beebleblox/conf/textures/fire.png.bak and recreate the new file.
File conf/textures/portal.png is modified! I will create a backup to /home/beebleblox/conf/textures/portal.png.bak and recreate the new file.
Reading materials file...
ERROR: Error reading configuration file:
java.lang.Exception: Cannot open configuration file conf/default.mtl
	at org.jmc.Materials.readConfig(Unknown Source)
	at org.jmc.Materials.initialize(Unknown Source)
	at org.jmc.Main.runGUI(Unknown Source)
	at org.jmc.Main.main(Unknown Source)

ERROR: Cannot check update 
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.jmc.util.Xml.loadDocument(Unknown Source)
	at org.jmc.CheckUpdate.isAvailable(Unknown Source)
	at org.jmc.CheckUpdate$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

No update available...

**Comment by Beebleblox** [comment]
AND (I really should do it all in one thread) when I select the world I want to load, the Console says "Error parsing dimension "SPACESTATION3"! Skipping..." That might be one of the problems

**Comment by danijel3** [comment]
The program is refusing to work because it wasn't able to extract the configuration files. You need to put the JAR in a folder that is user write-able. You think that's possible?

**Comment by Beebleblox** [comment]
Tell me how and we shall see. Thanks

**Comment by danijel3** [comment]
Try moving the JAR file to a folder you are sure to have write permissions, like Desktop or Documents. If it works there, you can make a folder wherever you like and change permissions there.

**Comment by Beebleblox** [comment]
Either I've done it wrong or it doesn't work

**Comment by danijel3** [comment]
Can you try this command:

`jar xf jMc2Obj-dev_g22.jar conf`

in the same directory as the JAR file and then run it again and see if it works?

**Comment by Beebleblox** [comment]
In the Linux terminal or the console?

**Comment by danijel3** [comment]
In your OS terminal.

**Comment by danijel3** [comment]
You can usually right-click in the folder in your file browser and choose "Open terminal here" or something similar to open the terminal in the right folder.
