### ISSUE TITLE
Will JMC Support Minecraft 1.13+?

### ISSUE THREAD

**Issue by ghost** [jmc2obj/j-mc-2-obj#114]
Since they literally re-coded all the blocks, blocks ID do not longer exist, because of this jmc broke and no longer works in 1.13+ but it still does in 1.12.2-

When you try to open a world in jmc it shows a black map and all options are disabled, because jmc is trying to look for IDs and there aren't any then the world doesn't exist for jmc

**Comment by danijel3** [comment]
I haven't played Minecraft in ages. Can you give some more insights in what really happened that it doesn't work?

**Comment by danijel3** [comment]
Thanks, that's helpful. It may be the issue is purely in the configuration, but we'll have to check for sure.

**Comment by davidzallen** [comment]
Any update on this? Still stuck on 1.12, really looking forward to using the new blocks but I can't as of now.

**Comment by mmdanggg2** [comment]
I'm having a look at it now, at the moment it is having trouble parsing the nbt tags in the region files... I hope that's all that's wrong if it is i might have a fix soon.

**Comment by mmdanggg2** [comment]
Ok, the new TAG_Long_Array was easy enough to add but the entire block storage format is different and there really are no longer block id's so we are either going to need to convert from text back to the id's which feels like it would be a temporary hack or totally refactor how we are dealing with blocks which would be a lot of work!

**Comment by davidzallen** [comment]
I'd be happy to help, regardless of how long it takes, as long as I know what to do :p 

My animation team uses JMC for our animations and getting this working and updated again for the new Minecraft would be amazing. I've also added a few custom additions to JMC on our end which I'd be happy to share as well :)

**Comment by danijel3** [comment]
I agree that converting to IDs is not too productive, especially since the game will most likely evolve beyond the existing IDs, so that would work for a short while.

Is it really that bad to refactor to the new tag? Or is most of the work going to involve recreating the configurations - in which case @davidzallen could probably help out.

**Comment by mmdanggg2** [comment]
I didn't really look into how much needs to be done to internally switch to string based id's but i presume a decent amount of the code will need changing in some way to accommodate that change. I'm looking into converting the id's at the moment, we would need some way of doing this to retain backwards compatibility anyway and we need to have a reader for the new format regardless of how we deal with id's internally. We could then work to switch to string id's after.

**Comment by mmdanggg2** [comment]
Just got the chunk format working! Only a few blocks are being converted at the moment so it's mostly coming out as stone right now but I get a successful export!
![image](https://user-images.githubusercontent.com/3161587/46311474-3777ff00-c5ba-11e8-8b39-678991255f64.png)

**Comment by davidzallen** [comment]
Awesome!

**Comment by mmdanggg2** [comment]
I managed to switch block id's internally to use strings now, so currently it will only work on 1.13 but it does seem to work fine! the blocks.conf needs to be switched over, would be great to have a hand with that. block data is currently ignored so that needs working out but good progress! 
![image](https://user-images.githubusercontent.com/3161587/46507513-bc6c4e00-c830-11e8-9696-3ed986ee9c75.png)

**Comment by davidzallen** [comment]
I can get started on the blocks.conf right away. How can I get the current .jar file so I can test it as I work with it?

**Comment by mmdanggg2** [comment]
Yea, go ahead, I would avoid any blocks with data for now though. You can try ones where its just different variants eg. planks. you can [look at the diff](https://github.com/jmc2obj/j-mc-2-obj/commit/64f3a8539d5c90a95e028402a446007ac6f414fb#diff-726da239c3f16553d2a646cfa7de637d) to see what I did with some of them. The [wiki page on the flattening](https://minecraft.gamepedia.com/1.13/Flattening) is super useful for knowing the new names.

here is a build of d4d7f7079e9caec34466e590d0c7b46490328d91
[jmc2obj.zip](https://github.com/jmc2obj/j-mc-2-obj/files/2448576/jmc2obj.zip)

**Comment by davidzallen** [comment]
Thanks, I'll start working on it tonight.

**Comment by Arbiter617** [comment]
I got a bit beyond half way through the blocks, but then got stuck trying to get a programming environment working opposed to just using Notepad++ as I have been. 

Over the last year, my friend and I added a few new .class files to the "models" which allow for different blocks, and I'm wanting to add that back into this branch but I'll have to either wait until my friend's around again so he can add it, or find a way to edit these .class files.

**Comment by Arbiter617** [comment]
Have you tried choosing which blocks to import? By default, many of mine are unchecked (making it hard to tell if it's reading new blocks being added to blocks.conf), and upon checking them I'm getting a lot of errors in the console. 

https://gyazo.com/621c4657858875d11906812da899285a

**Comment by Arbiter617** [comment]
Nearly done with the blocks.conf!

It may need the two new models (Path, and Plant) which I've added to my own JMC in the past, but are no longer in this branch. 

If you're able to add these to the program, here they are:
https://pastebin.com/eywpcxGW
https://pastebin.com/gq1fJ0TA

Otherwise I'm still awaiting availability of my friend who added these last time. 

The Path model is used for the Path block that was added a few updates ago. It was similar to Farmland but slightly different texture-wise. I'll be adding that block and most other new ones to the blocks.conf.

The Plant one is something I did which helps plants behave like they do in Minecraft (looks loads better.) I'll get some pictures to show more specifically after finishing up the .conf.

**Comment by Arbiter617** [comment]
Finished going through the blocks.conf. I decided to actually hold off on the new blocks for the moment. I also skipped over (and commented out, so we can easily find) the blocks which seem to be relying on the new "states" which I think is what you were saying earlier about blocks with data.  

Here's what it looks like at the moment, although I'm still having the problems with choosing the blocks to export:
![c187f0f0b3c594a934c96ac473f148b7](https://user-images.githubusercontent.com/7040727/46559027-dbf08e80-c8a3-11e8-900b-0975cf7fbaf9.jpg)

I don't seem to be able to attach the file directly here, and I'm unsure of how (or if I even can) add it directly into the github. Here's a download link:
https://drive.google.com/file/d/1Jm2JagR5eCzvJgrkN6uO_cjo4FHbeKYz/view?usp=sharing

**Comment by Arbiter617** [comment]
After a quick skim through the unchecked exported blocks, they're all blocks which I changed the names of, or added new. For instance previously there was just "Wool" but now there's "Blue Wool" and all the rest. So Blue Wool isn't selected, as with all other colors. Then things like "Oxeye Daisy" aren't selected, because that had to be added now that flowers are separated into individual blocks.

Not sure if this helps, but at least it's clear which are and aren't being selected.

**Comment by mmdanggg2** [comment]
I think its just loading a config where it just has the old block list, so new ones aren't checked by default.

Great work with the blocks.conf, I'll get those other models added too!

**Comment by Arbiter617** [comment]
**Elaboration on my Plant model:**

Previously JMC was using the "Cross" model on things like grass, which caused the grass to extend from corner to corner, and then extend 1 block unit upwards. This meant that the planes being created were actually much wider than they were tall.

In actual Minecraft, they are a bit less wide, and are even randomly offset a bit per block. In addition, they are randomly mirrored.

You can see here a gif I put together. The first image is what the plants looked like in JMC when using the Cross model. The second image is with my Plant model, which is how it behaves ingame, and you can ignore the third, as it's just demonstrating varied heights (which I did in Blender, not with JMC)

https://gyazo.com/4aa7c320da5386ff7bf053681e653349

**Comment by Arbiter617** [comment]
Figured I'd throw this up on Drive as well. This is a really helpful **map for testing JMC**. I basically laid out almost every block (as of 1.12 I think), and did so in order of (the now expired) block IDs. So if you're testing to see if a specific block is/isn't working, it's very easy to find.

https://drive.google.com/file/d/1jDAICfZhR2K_rMfDVCczmuYFhR8wPO8y/view?usp=sharing

**Comment by Arbiter617** [comment]
It was actually pretty easy to go through even without testing, mostly just renaming and re-alphabetizing (which took the most time- checking to see if the texture already existed but by a different name.)

I got up to "g" tonight, I'll definitely try to have it done sometime tomorrow.

**Comment by mmdanggg2** [comment]
I thought when you said you had coding working you had the repo setup with the latest commits. You could just run it with eclipse then. We don't have an automatic build system in github so you'll have to build it yourself or i'll just give you the latest when something major changes.

Here is the latest build 968879d35928c2e07546d1f65c4b14ca7d638299
[jmc2obj.zip](https://github.com/jmc2obj/j-mc-2-obj/files/2453108/jmc2obj.zip)

**Comment by Arbiter617** [comment]
I have something in eclipse working where if I have the most up-to-date .jar, and download the .zip off github, then I'm able to edit the code (such as the models) and run it from there.

I'm just unsure of how to get the .jar's still. I'll grab this one now and keep going through the texsplit.

**Comment by mmdanggg2** [comment]
You shouldn't need a .jar to run it from eclipse. Eclipse creates the jar from the source code.

looks like this? 
![image](https://user-images.githubusercontent.com/3161587/46574112-792bef80-c996-11e8-898b-92fef159b41b.png)

and the run config
![image](https://user-images.githubusercontent.com/3161587/46574115-8c3ebf80-c996-11e8-891b-1e9a468f4375.png)

**Comment by Arbiter617** [comment]
Interesting, I'll see if I can get it running like that with the .zip alone!

Do you have any better way to contact you, such as Discord? Got just a few quick questions about the texsplit.

**Comment by mmdanggg2** [comment]
Discord: mmdanggg2#3029

**Comment by thewalkingcrafters** [comment]
Is a basic, pre-release version ready for basic use on a Mac? or do we have to wait some time?

**Comment by TotiGonzales** [comment]
I think they moved to the discussion to discord and will update this thread as soon as they have something done. @Arbiter617 I would love to talk with you about models in Jmc2Obj if you want you can contact me over discord at TotiGonzales#8576.

**Comment by mmdanggg2** [comment]
@thewalkingcrafters If you really want to try the version we have now, here is a build of 71369d5c697406f0a8fab7c40b00c208d1365513 this only works on 1.13 maps, many of the new blocks are missing still and not all blocks export correctly.

[jMc2Obj-dev_g9.zip](https://github.com/jmc2obj/j-mc-2-obj/files/2568469/jMc2Obj-dev_g9.zip)

**Comment by Arbiter617** [comment]
For anyone following this thread, we've come quite far with the 1.13 work. I had to take a break for about 3 weeks to work on other stuff, but this is where we're up to as far as supporting the new 1.13 blocks:
https://gyazo.com/dfcb0caf37abd02939b93720e037ec98

I should be able to get the remaining blocks sorted asap

**Comment by thewalkingcrafters** [comment]
nice. @mmdanggg2 thanks for the build! Much appreciated!

**Comment by Danielv123** [comment]
Any progress on this? Latest build keeps erroring with ```Found unknown block id: minecraft:comparator
ERROR: Uncaught exception in thread: Thread-8
java.lang.ClassCastException: org.jmc.NBT.TAG_Byte_Array cannot be cast to org.jmc.NBT.TAG_Int_Array
	at org.jmc.Chunk.getBlocks(Chunk.java:206)
	at org.jmc.Chunk.renderImages(Chunk.java:325)
	at org.jmc.gui.ViewChunkLoaderThread.run(ViewChunkLoaderThread.java:182)
	at java.lang.Thread.run(Unknown Source)
```

and similar on all maps I can find.

**Comment by mmdanggg2** [comment]
> Any progress on this? Latest build keeps erroring with
> 
> ```
> Found unknown block id: minecraft:comparator
> ERROR: Uncaught exception in thread: Thread-8
> java.lang.ClassCastException: org.jmc.NBT.TAG_Byte_Array cannot be cast to org.jmc.NBT.TAG_Int_Array
> 	at org.jmc.Chunk.getBlocks(Chunk.java:206)
> 	at org.jmc.Chunk.renderImages(Chunk.java:325)
> 	at org.jmc.gui.ViewChunkLoaderThread.run(ViewChunkLoaderThread.java:182)
> 	at java.lang.Thread.run(Unknown Source)
> ```

This is probably caused by loading a map that was converted from 1.12 but not fully. Minecraft only converts chunks when they're loaded so you will need to go to every chunk in the world to make them convert...

**Comment by Arbiter617** [comment]
> Any progress on this?

We have a build working almost perfectly with 1.13+ now, but as mmdanggg mentioned it will not work with pre 1.13 maps which have not had a player load the chunks in 1.13.

There are just a few more improvements/fixes that need to be done then I think it should be about ready for a more public release. We haven't just been adding the new blocks, but also going back and fixing some problems that have existed for awhile.

**Comment by thewalkingcrafters** [comment]
For those that get errors I suggest to use the “optimize world” option in minecraft. This will check for every chunk and turn it into a 1.13 chunk without need to load them manually

**Comment by Jaspooky** [comment]
Will there be any support for the Structure `.nbt` file format or the Sponge `.schem` format, or does the program strictly only handle world files?

**Comment by mmdanggg2** [comment]
> Will there be any support for the Structure `.nbt` file format or the Sponge `.schem` format, or does the program strictly only handle world files?

Not currently any plans but it probably wouldn't be out of the question.

**Comment by mmdanggg2** [comment]
Alright, we've got 1.13 working well enough now so I've added a build to the [GitHub releases page](https://github.com/jmc2obj/j-mc-2-obj/releases)!
It should also pick up on updates when we add newer releases to github.

**Comment by Flowerscow** [comment]
Far Why?
![74555](https://user-images.githubusercontent.com/50837109/63187431-8e1de880-c067-11e9-9d03-1d64ab95fac0.png)

**Comment by Flowerscow** [comment]
@mmdanggg2  Far, Why not?

![74555](https://user-images.githubusercontent.com/50837109/63206868-6a898b00-c0c5-11e9-8ea6-314b3d226bcd.png)

**Comment by mmdanggg2** [comment]
> @mmdanggg2 Far, Why not?

What does that mean? Is there not a more detailed error?

**Comment by Flowerscow** [comment]
Sorry memory error is shaking thanks well
