### ISSUE TITLE
Jmc2Obj Updater

### ISSUE THREAD

**Issue by TotiGonzales** [jmc2obj/j-mc-2-obj#115]
I've been seeing this pop up on Reddit multiple times tho I couldn't seem to be able to find any issue thread here.

Every time you launch the latest version that you can currently get on the website this message will pop up:
![error message](https://user-images.githubusercontent.com/38110890/48300875-c561d680-e4e4-11e8-9c71-079f0902b748.png)
This is what the console says:
![console](https://user-images.githubusercontent.com/38110890/48300879-cf83d500-e4e4-11e8-92c6-c083745a2c94.png)

This doesn't really hinder the user from using Jmc2Obj as its merely an updater problem. Tho seeing the work that gets put into getting it to MC 1.13 I think it's very important to have this working.

**Comment by mmdanggg2** [comment]
This should have been fixed by c4533772cc808aafbd9b94608a65d24ef24037c1, updated jar isn't available on the website yet.

@danijel3 maybe update the website download?

**Comment by mmdanggg2** [comment]
Updates have now been changed to use GitHub releases.
