### ISSUE TITLE
Fences and iron fences aren't connected together

### ISSUE THREAD

**Issue by Omegafoxx** [jmc2obj/j-mc-2-obj#116]
When i use the V 103 the fences and iron bar aren't connected. it's not a texture problem, only a mesh weird trick not enabled ? :/

**Comment by mmdanggg2** [comment]
hmm, could you provide more details, seems like bars and fences do not connect in minecraft and jmc2obj seems to match this fine: 
![image](https://user-images.githubusercontent.com/3161587/54390390-44853800-469a-11e9-9efd-348c54e9ea91.png)

**Comment by Omegafoxx** [comment]
![image](https://user-images.githubusercontent.com/32814162/54405178-1d218000-4719-11e9-8933-135af172781a.png)

![2019-03-15_11 51 53](https://user-images.githubusercontent.com/32814162/54405199-2874ab80-4719-11e9-8b1f-9bf85a0257e9.png)

**Comment by Omegafoxx** [comment]
![image](https://user-images.githubusercontent.com/32814162/54405433-e6983500-4719-11e9-9a04-3a2723e2105d.png)
EDIT: when i load the chunks in minecraft before exporting it in jmc2obj, the fences are well connected...

**Comment by mmdanggg2** [comment]
That looks to be an issue with Minecraft's world updater, it must not update to the new block states when you use the optimise world option. I don't think there's much we can do about that.
