### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by CV01HatsuneASD** [jmc2obj/j-mc-2-obj#118]
Maybe the git repositories have the latest code edits...

**Comment by danijel3** [comment]
If you're looking for the latest release, it's on the releases page here:

https://github.com/jmc2obj/j-mc-2-obj/releases

I've updated the main website to reflect this fact.

To compile the project yourself, simply clone/download this repo and use the Ant build.xml file provided.

**Comment by CV01HatsuneASD** [comment]
> If you're looking for the latest release, it's on the releases page here:
> 
> https://github.com/jmc2obj/j-mc-2-obj/releases

The latest release wasn't working properly in my system. The world was generated in Minecraft 1.14 launched through Shiginama Launcher. It outputs no textures.

> To compile the project yourself, simply clone/download this repo and use the Ant build.xml file provided.

But how? What compiler?

**Comment by danijel3** [comment]
The program is written in Java. You have to have JDK installed and also get the Apache Ant program. Then you simply run `ant` ant it will be built for you.

**Comment by CV01HatsuneASD** [comment]
Thanks for the help. I'll going to close this issue, but you may leave your reply if you have an idea how to fix my problem. Right now it's still showing black screen when importing. And when exporting, it was blank.
