### ISSUE TITLE
FTB Maps

### ISSUE THREAD

**Issue by MBoberski** [jmc2obj/j-mc-2-obj#119]
Hello,

is there a way to export maps from FTB modpacks? Or if there will be that in future versions?

TIA

**Comment by mmdanggg2** [comment]
You should be able to export maps with mods without major issues, of course, all modded blocks will not be recognised. You can easily add custom entries to your blocks.conf in the conf folder if they are simple cubes or variants of minecraft blocks.

I don't think we can add official support for modded blocks, there's too many mods, all with their own quirks.

If somebody wants to make a fork or branch for supporting specific mods like those in FTB then please do!

**Comment by TorchwoodPL** [comment]
There is a problem, save from modded minecraft are not loading into app.

```
ERROR: Uncaught exception in thread: ViewChunkLoader
java.lang.ClassCastException: org.jmc.NBT.TAG_Int_Array cannot be cast to org.jmc.NBT.TAG_Byte_Array
	at org.jmc.Chunk.getBlocks(Chunk.java:210)
	at org.jmc.Chunk.renderImages(Chunk.java:383)
	at org.jmc.gui.ViewChunkLoaderThread.run(ViewChunkLoaderThread.java:182)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by TorchwoodPL** [comment]
Also small tutorial on blocks.conf would be nice

**Comment by mmdanggg2** [comment]
Hmm, what versions are you using: jmc2obj, minecraft, FTB, launcher?

**Comment by MBoberski** [comment]
jmc2obj: build 106
minecraft: 1.12.2
FTB: FTB Builders Paradise
launcher: Twitch

**Comment by mmdanggg2** [comment]
The latest jmc2obj versions only support 1.13 and up at the moment, you will need https://github.com/jmc2obj/j-mc-2-obj/releases/tag/50 for it to maybe work. Although after looking at that error, it probably won't. Give it a try anyway.

**Comment by MBoberski** [comment]
The same error.

**Comment by mmdanggg2** [comment]
Try this, it should just ignore biomes.
[jMc2Obj-dev_g9.zip](https://github.com/jmc2obj/j-mc-2-obj/files/3254133/jMc2Obj-dev_g9.zip)

**Comment by MBoberski** [comment]
There is no error but also there is nothing on map. Here you have Save file I tested on, its a flat world with some blocks on spawn.
[Builder.zip](https://github.com/jmc2obj/j-mc-2-obj/files/3254154/Builder.zip)

**Comment by mmdanggg2** [comment]
Nope, sorry, not going to work, the modpack uses a mod called [JustEnoughIDs](https://minecraft.curseforge.com/projects/jeid) which changes the chunk format to a weird blend between 1.12 and 1.13.

**Comment by MBoberski** [comment]
So you are not planning on adding support for that?

**Comment by mmdanggg2** [comment]
No, I don't think I will, not anytime soon anyway, even if that custom format was supported, you would still have to implement all the modded blocks. I might look at it if I'm particularly bored one day.
As I said earlier, anyone else is welcome to make a fork/branch for mods.

**Comment by MBoberski** [comment]
If you add proper chunk chandling I will add mod item definitions :)

**Comment by mmdanggg2** [comment]
It's not just reading chunks, because it's 1.12 all the block data and ids will be int's and bytes so it would need to be converted. We could fork from the pre 1.13 version but then all this work would be completely incompatible with anything going forward. I did want to get conversion from the old ids to the new strings going at some point, I might look at this after that is working but i'm not sure when or if that will happen.

**Comment by danmartinez78** [comment]
Any update on this?
