### ISSUE TITLE
Slow command line texture exporting

### ISSUE THREAD

**Issue by TheDuckCow** [jmc2obj/j-mc-2-obj#122]
I found that exporting from command line is quite slow. Some references:

_To export all 717 images from the vanilla pack_
- 6 minutes via UI (where the jar was launched from command line, and so I have a console window constantly printing out progress/logs)
- 4 minutes via UI (directly launched from jar, not from a console window)
- 13 minutes via command line, no UI (but also exports alpha passes, which the two above don't, and I don't need)

Another odd point is what it appears to be attempting to do:
in bullet 2 above, I get console print outs like:
```
Creating Buffer Image
Creating Texture File: wither_painting
Writing Texture File: wither_painting
```

But when exporting textures via command line (no UI), I get messages like this:
```
.Creating Buffer Image
Creating Texture File: bamboo_small_leaves
Writing Texture File: bamboo_small_leaves
Trying normal map
Error loading normal texture: Couldn't find assets/minecraft/textures/block/bamboo_small_leaves_n.png in 1.14.4.jar
Trying specular map
Error loading specular image: Couldn't find assets/minecraft/textures/block/bamboo_small_leaves_s.png in 1.14.4.jar
```

It seems to be doing some additional extra, unnecessary checks for passes even when the texture pack does not have this (or perhaps it's always doing this check, but it just happens to not print out the normal and spec pass checks when running from the UI). That plus console printing might be slowing the system down. To that end, I need to test if this just gets faster if called from another program where the stdout pipe is just ignored. 

Sample command I'm using below to export textures via command line (note in my time estimates above, I'm basing time to export textures from the timestamp of first image versus last image saved, so the obj export time is not included)

```
java -jar ./jMc2Obj-107.jar --dimension=0 --area=-80,120,-20,170 --height=0,256 \
  --render-entities --object-per-mat \
  --output=//test_jmc_b/ \
  --objfile=text_exp.obj --mtlfile=text_exp.mtl \
  --export=obj,mtl "//minecraft/saves/WorldGenB-1_14_4" # personal paths replaced by //
```

Final note: I also notice that the command line example above exports really two images for each block, the diffuse and the alpha b/w image. I'm realizing now this is probably the source of maybe all of the extra slowness, though it seems slightly more than just 2x slower compared to the direct UI.

Is there a command line flag to specify not exporting of alpha passes? I can try again with this if it exists.

**Comment by mmdanggg2** [comment]
I'm don't know how much extra time the alphas take to export but i know that checking for the normal maps and specular maps takes a surprising amount of time. I changed the defaults in the UI to not bother checking recently with some extra checkboxes to enable it but I didn't add new command line parameters to go along with it so it will always check when running command line.

I can easily add these in, not sure what would be the best format for the command. I could just add more codes to the --export option but I feel like it may be better to add a new --exporttex or something with alphas, normals and speculars as optional. Thoughts?

**Comment by TheDuckCow** [comment]
Just so I'm clear, you mean adding an option like `--export=main,alpha,spec,normal`? If so, I think that makes the most sense, and is consistent with the export=obj,mtl,tex semantic, and you can set it so that the default state is all of them enabled (as the command line currently does). 

All this being said, I still wonder why simply checking for the other passes causes such a delay even when they don't exist. I think it might be because a new zipfile reader is being created and torn down every time to check for path names, as opposed to checking once and keeping a reference of what's available in memory. At least, that's what I gather is [happening here](https://github.com/jmc2obj/j-mc-2-obj/blob/master/src/org/jmc/TextureExporter.java#L280). It might speed things up significantly if you were to just do a straight memory copy of all the file paths from the textures folder at the start of that function (and then loop over only those explicitly found files instead of checking and breaking). It's been quite awhile since I've touched Java, but willing to give it a try unless you get to it sooner.

**Comment by mmdanggg2** [comment]
Yes, a `--tex_export` option is exactly what i had in mind. Hopefully i can get round to that tomorrow. If you want to have a crack at optimising the texture exporting process then please do. I profiled it a while ago and i think it was the loadImageFromZip that was causing the slowness, most likely the reason you stated. Make sure you work from the 1.13Anvil branch, that's where latest is rn.

**Comment by TheDuckCow** [comment]
Will do - I'll see what I can get to over the next week(s), thanks for the branch reference.

**Comment by mmdanggg2** [comment]
I've made a quick tex_export command. It might be horrifically broken, the texture export code is a mess and the command code was set up to always export the world which you might not want to do if you just want the textures. It seemed to work on the couple of tests i did, let me know if it is working. Pretty hacky at the moment, I might redo the command code.

**Comment by TheDuckCow** [comment]
Thanks for that, pulled down the changes now (and starting to do the work on the mentioned optimization, was able to make some progress already).

Your new flag seems to work on just exporting the textures, but when I try to provide a `--texturepack=` option to specify the source pack, it then appears to use the default export options of exporting out the obj file (where without adding the `--texturepack` option, it would not export the obj, as would be expected). Sample command that creates this:

```
java -jar ./JAR/jMc2Obj-108.jar \
  --dimension=0 --area=-10,-10,10,10 --height=0,256 \
  --render-entities --object-per-mat \
  --output=./test/ --objfile=test_jmc2_cmdlin.obj \
  --mtlfile=test_jmc2_cmdlin.mtl --tex_export=base,norm,alpha \
  --texturepack="{PATH}/resource_packs/S&K 64x PBR.zip" \
  "{PATH}/saves/WorldGen 14_3"
```

So notice that admittedly, the arguments are a bit "illogical" in that I specify an obj and mtl name, but not actually the -export flag. But even excluding the `--objfile` and `--mtlfile` flags still makes the latest anvil.13 branch export the obj file to a default name.

**Comment by mmdanggg2** [comment]
That seems like that's correct by the command docs, I made it so it exports when you specify a world directory so you could run it without exporting an obj and just textures. The code was only ever intended to run as though you were exporting the world. Like i said, it's a bit hacky atm.

**Comment by TheDuckCow** [comment]
Flagging the pull request above, happy to assist with any review walkthrough, but do see the note about doubly verifying no changes to export behavior and files output.

In terms of the export behavior, just want to make this point clear, see points below comparing two nearly identical commands:
- Command one *will not* export an obj file
- Command two *will* export an obj file, the only change was specifying a texturepack to use in the export instead of relying on the default. 
- Understood it being a hack, just wanted to make the situation clear - I think it would make sense for it to behave (ie exporting obj or not) the same way regardless of there being a `  --texturepack` flag. 
- Personal reference would be to have it not export an obj if export=obj,mtl is not specified! But at worse, I can just have it export a 1x1x1 block so it's honestly not a huge issue. 

Command one:
```
java -jar ./JAR/jMc2Obj-108.jar \
  --dimension=0 --area=-10,-10,10,10 --height=0,256 \
  --render-entities --object-per-mat \
  --output=./test/ --objfile=test_jmc2_cmdlin.obj \
  --mtlfile=test_jmc2_cmdlin.mtl --tex_export=base,norm,alpha \
  "{PATH}/saves/WorldGen 14_3"
```

Command two:
```
java -jar ./JAR/jMc2Obj-108.jar \
  --dimension=0 --area=-10,-10,10,10 --height=0,256 \
  --render-entities --object-per-mat \
  --output=./test/ --objfile=test_jmc2_cmdlin.obj \
  --mtlfile=test_jmc2_cmdlin.mtl --tex_export=base,norm,alpha \
  --texturepack="{PATH}/resource_packs/S&K 64x PBR.zip" \
  "{PATH}/saves/WorldGen 14_3"
```

**Comment by TheDuckCow** [comment]
Just wanted to follow up here, in case you want to still consider this optimization pull request. I think this will be a good optimization to include, and important for embedded use cases I'm working on:
https://github.com/jmc2obj/j-mc-2-obj/pull/124

**Comment by mmdanggg2** [comment]
Yea, sorry I keep meaning to have a look at this. I agree, it probably shouldn't export unless those options are specified, I'll try to find some time to fix this soon.

**Comment by TheDuckCow** [comment]
Confirming as per https://github.com/jmc2obj/j-mc-2-obj/pull/124, this is now in master.
