### ISSUE TITLE
Can't find minecraft.jar

### ISSUE THREAD

**Issue by RexTheCapt** [jmc2obj/j-mc-2-obj#123]
I am not using minecraft with it's regular launcher and file locations. I am using the twitch launcher to play with multiple versions and easy management with mods and resrouce packs. With the twitch launcher the minecraft.jar files is download to a another folder than in %appdata%. It would be nice if you had the option to select the minecraft.jar your self.

**Comment by mmdanggg2** [comment]
You can already do this, you just need to choose export from resource pack and change the file type to all and select the minecraft jar, usually in .minecraft/versions/x.x.
