### ISSUE TITLE
Mac Texture Export

### ISSUE THREAD

**Issue by KarlMarshallNext** [jmc2obj/j-mc-2-obj#125]
ERROR: Error saving textures:
java.lang.RuntimeException: Cannot create texture directory!
	at org.jmc.TextureExporter.mergeTextures(TextureExporter.java:558)
	at org.jmc.gui.ExportWindow$13.run(ExportWindow.java:1184)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by EmeraldTNTking** [comment]
This is happening to me too, did you fix it?

**Comment by madhav132** [comment]
i am also facing this right now..
have you done this error?

**Comment by jacklynn-yan** [comment]
I found a way to fix this. You have to go to the file directory you want to export the textures and the obj files to and create a folder called tex then export the textures to the folder which encloses the tex folder. After this, make sure to export the obj files to the same folder that encloses the tex folder. 

I think the root problem involves something with MacOS permissions not allowing programs to mess with folders.

**Comment by mmdanggg2** [comment]
I think this is similar to #127 - Mac OS not allowing folder creation...

**Comment by 09DanielACE** [comment]
It didn't open on my Mac too
