### ISSUE TITLE
jmc cant open conf/default.mtl on Linux

### ISSUE THREAD

**Issue by Zophiekat** [jmc2obj/j-mc-2-obj#127]
Im not really sure whats the problem here, but whenever i run the jmc2obj.jar file i get this message
![Screenshot from 2019-10-19 14-04-21](https://user-images.githubusercontent.com/47702767/67150647-d6cc6a80-f27f-11e9-891a-310bea840fbf.png)
![Screenshot from 2019-10-19 14-15-46](https://user-images.githubusercontent.com/47702767/67150649-dc29b500-f27f-11e9-970b-5ce244c4e0c0.png)
Im using Jmc2Obj-107.jar, Minecraft 1.14.4, and Linux Pop!_os 19.04, I have the latest Java version installed as well.

hep plz >n<

**Comment by PainKKKiller** [comment]
Have the same problem. It seems this program not working at all

**Comment by PainKKKiller** [comment]
Found how to solve it here https://github.com/jmc2obj/j-mc-2-obj/issues/113

**Comment by mmdanggg2** [comment]
It would be good to know what folder you are running it in, what permissions it has and how you are starting jmc.

**Comment by Zophiekat** [comment]
ah yea.. i already solved this long ago- sorry for not writing an answer.
it had to do with permissions or whatever, i dont know why, but jmc can only run from the home directory, in fact, any .jar i have in my system can only be run in my home directory, move it an extra folder outside of it and it runs with problems. it is more of a solution more than an answer but it works for me exceeeeept that my home directory is a mess

**Comment by danijel3** [comment]
It has to do with how your user account is setup. If you use an admin account, you'd probably have permission to run everything everywhere. With user accounts, you need to explicitly allow which folders are usable for what purpose. 

We considered alternativne solutions for storing config files, but nothing was really more convenient than the current solution. Even Minecraft uses the hidden settings dir which is hard to locate for the average user.

**Comment by mmdanggg2** [comment]
I'm gonna re-open this because it keeps happening. We should try to find a solution, or at least a more helpful error message...

**Comment by OttoTheCat** [comment]
I did not see this when I made my issue. For that I apologize but as I am on mac, i do not kno whow to write permission for .jar files.

**Comment by mmdanggg2** [comment]
I presume it can't create / write to the 'conf' folder next to the .jar file.

**Comment by OttoTheCat** [comment]
I put the jar file into the file and now it says this.

ERROR: Error reading configuration file:
java.io.FileNotFoundException: /Users/(My username)/Desktop/j-mc-2-obj-master/conf/default.mtl (Operation not permitted)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.jmc.Materials.readConfig(Materials.java:44)
	at org.jmc.Materials.initialize(Materials.java:95)
	at org.jmc.Main.runGUI(Main.java:68)
	at org.jmc.Main.main(Main.java:46)

Maybe you are write.

**Comment by jacklynn-yan** [comment]
What I did was manually put all the files where they should be. it can be a little confusing, but I don’t experience any problems once everything is in place. 

All you need to do is make sure the .jar file is in the same directory as the conf folder, and all other jmc2obj related folders, for example I left all the files in my downloads folder, and this has been fine.

For exporting obj models with proper textures, make a folder where you want the files to be, then inside that folder create a new folder called tex. Export the Minecraft textures or textures from your custom resource pack to the folder enclosing the tex folder. Then export the obj to the folder enclosing tex as well. When you’re done, you should have an obj file, mtl file, and tex folder all in one folder, and inside the tex folder should be all the Minecraft textures. This is the same solution I offered in #125

**Comment by mmdanggg2** [comment]
If anyone that had this issue could try this new version to see if it gets around this problem, that would be good to get confirmation this fixes it.
[jMc2Obj-112-test1.zip](https://github.com/jmc2obj/j-mc-2-obj/files/6482405/jMc2Obj-112-test1.zip)
