### ISSUE TITLE
Image Texture node set to Linear instead of Closest in Blender import

### ISSUE THREAD

**Issue by Zophiekat** [jmc2obj/j-mc-2-obj#132]
when importing the .obj into blender 2.82, all image texture nodes are set to linear by default making the textures blurry, changing them to closest fixes the issue but would take forever to change every individual material back to closest. Can this be the default?

**Comment by mmdanggg2** [comment]
AFAIK this is a limitation with the OBJ/MTL file format, you can't change the texture filtering.

The best workaround is to make a script to change each texture, then it's a 1 click fix.

Another way is to just export the textures at 8x scale from jmc, then it will be less blurry with linear interp but you will use way more ram loading them and they will still be blurry close up; so it's not ideal.

**Comment by danijel3** [comment]
Another way would be to export Blender files directly, but then the project would be jmc2blend not jmc2obj. We considered this a long time ago, but people ususally figured out ways to deal with it. I'd look for some Blender extensions, if anyone's made them.

**Comment by vitrack** [comment]
Here's a python script to change the interpolation of all the textures of all the materials of the active object:
`import bpy
mats=bpy.context.active_object.material_slots
for mat in mats:
    nodes=mat.material.node_tree.nodes
    for node in nodes:
        if node.type=="TEX_IMAGE":
            node.interpolation="Closest"`
You can paste this into the text editor in blender, and run it.

**Comment by StandingPadAnimations** [comment]
MCprep also does all this

**Comment by Sirkku** [comment]
Just a FYI: I tried to implement COLLADA 1.4.1 and realized that Blender (3.0.0) nor Unity (2021.2.8) support the file format sufficiently, the supplied texture filtering gets ignored by Blender/Unity.
How to recreate a simple example:
1. create a new scene in Blender
2. add a material to the cube, give it a texture and link it to the BSDF.
3. export as COLLADA .dae
4. add `<magfilter>NEAREST</magfilter><minfilter>NEAREST</minfilter>` to the `<sampler2D></sampler2D>` entry in the .dae file
5. Import the modified .dae into a fresh project in Unity or Blender

**Comment by Macintosh-Fan** [comment]
This script works for me instead for some reason. I'll leave it here just incase.
```py
import bpy

for mat in bpy.data.materials:
    if not mat.node_tree:
        continue
    for node in mat.node_tree.nodes:
        if node.type == "TEX_IMAGE":
            node.interpolation = "Closest"
```
