### ISSUE TITLE
Chunk skipping with 1.12 world

### ISSUE THREAD

**Issue by T0biasCZe** [jmc2obj/j-mc-2-obj#134]
Hi, everytime i try to export 1.12.2 world, it throw chunk is old type, skipping error.
It throw even with freshly generated world

**Comment by mmdanggg2** [comment]
The current version of jmc2obj doesn't support minecraft versions below 1.13 due to a massive change in how the data is stored in 1.13 and above. You'll have to use [this version](https://github.com/jmc2obj/j-mc-2-obj/releases/tag/50) to export 1.12 and below.
