### ISSUE TITLE
Black Screen on version jMC2obj-108 when accessing earlier versions of worlds

### ISSUE THREAD

**Issue by dramdram** [jmc2obj/j-mc-2-obj#137]
I recently moved from Mineways to jmc, since their RAM usage wasn't very optimised for exporting large worlds.

Anyways, I have just tried to export a world that was in an older version. It showed nothing but the green cross, the red cross and a black screen. However, when I opened a world that was made in 1.15, it worked completely fine. Within the console it had said that it was **skipping old chunks**.  I don't know if this is just me, but help would be appreciated. I have looked around on the internet and saw something similar to this but it was from a while ago and was on Linux OS. I am on Windows. Apologies if I missed on anything, I am a newbie :3

I will leave a video below so you are able to see what I mean
https://youtu.be/HIaHnbUNLoc

**Comment by dramdram** [comment]
Only fix that I've found for this is to upgrade the world to a newer version ^^^

**Comment by mmdanggg2** [comment]
The latest version only support version 1.13 and later for now.
You can try and use this version for 1.12 and before https://github.com/jmc2obj/j-mc-2-obj/releases/tag/50
