### ISSUE TITLE
Due to The 1.16 data value change, all walls are being unconnected.

### ISSUE THREAD

**Issue by uran247** [jmc2obj/j-mc-2-obj#140]
Since version 1.16, block states for connection of walls are taking three values(low/none/tall) instead of two values(true/false).
As a result of this change, when convert a 1.16 world, all of the wall blocks will be treated as unconnected.

**Comment by mmdanggg2** [comment]
Fixed with 6120df0c02a5445b2ce1dedf0fa3b080627f0431
