### ISSUE TITLE
Support for 1.16?

### ISSUE THREAD

**Issue by Zophiekat** [jmc2obj/j-mc-2-obj#141]
when will there be support for 1.16 blocks and models? I'd add them myself but idk how jmc inner workings work

**Comment by mmdanggg2** [comment]
For most blocks it is a case of adding the definition to blocks.conf, material properties in default.mtl and the texture location in the textsplit.conf
Rough example here https://github.com/jmc2obj/j-mc-2-obj/commit/4b957af23d9fbf53be870d215bf566438838da71
Not sure if/when I'll get round to it.

**Comment by Zophiekat** [comment]
I began work on adding them a couple of days ago lol, and since I'm also taking the time to do stuff I thought it would be nice to re-organize, re-name stuff to be in their debug world order,

[jmc edit.zip](https://github.com/jmc2obj/j-mc-2-obj/files/5433869/jmc.edit.zip)

 I'm also changing the Kd values of all blocks to better match their texture colors, 
![Screenshot from 2020-10-24 17-32-13](https://user-images.githubusercontent.com/47702767/97094988-b2883400-161f-11eb-93fb-523fb805a871.png)

![Screenshot from 2020-10-24 17-28-47](https://user-images.githubusercontent.com/47702767/97094991-b87e1500-161f-11eb-8fd9-98fa36b42f26.png)

![Screenshot from 2020-10-24 17-36-18](https://user-images.githubusercontent.com/47702767/97094995-bddb5f80-161f-11eb-9225-bcb33b31777e.png)

![Screenshot from 2020-10-24 17-36-26](https://user-images.githubusercontent.com/47702767/97094998-c2a01380-161f-11eb-890d-1b8c80f6ad86.png)

![Screenshot from 2020-10-24 17-36-57](https://user-images.githubusercontent.com/47702767/97094999-c59b0400-161f-11eb-9781-79693c638762.png)

I'm also also fixing stuff that I find broken along the way

**Comment by kilian3242** [comment]
@Zophiekat when downloading your jmc edit I just replaced the existing files with the same name as your files, is that what I'm supposed to do? because now almost every other texture is missing (I'm new to this, sorry for the dumb question

**Comment by Zophiekat** [comment]
ah thats because its not finished yet, i have still to add the rest of the blocks

**Comment by kilian3242** [comment]
ah ok I thought I did something wrong

**Comment by jacklynn-yan** [comment]
I am also working on making blocks from 1.16 export correctly. I can get everything working except walls connecting. If someone wanted to make that work you would be my hero. So far I only have worked on the blocks.conf file, so nothing new actually works yet.

**Comment by jacklynn-yan** [comment]
This is the fully updated blocks.conf file, it will allow for every block to be exported with a different material, but there will be no texture. To get a texture to work you can change the default.mtl file and the texsplit_1.13.conf to have the unrecognized blocks. But this is a good start. :D

[blocks.conf.zip](https://github.com/jmc2obj/j-mc-2-obj/files/5791773/blocks.conf.zip)

**Comment by Zophiekat** [comment]
pog! ill get texsplit to work

**Comment by Zophiekat** [comment]
I just updated the texsplit_1.13.conf file with all new block textures. all that's left is the default.mtl
[texsplit_1.13.conf.zip](https://github.com/jmc2obj/j-mc-2-obj/files/5792174/texsplit_1.13.conf.zip)

**Comment by kilian3242** [comment]
Awesome 👏

**Comment by mmdanggg2** [comment]
Great work guys, thanks for helping out. I'll merge #144 with some fixes soon. @Zophiekat if you have the mtl update that would be great to have too.

**Comment by Zophiekat** [comment]
I finished writing the default.mtl, unfortunately on export everything is pink, command window says it doesn't recognize the new block's id, what do you people think is the cause of this? @jacklynn-yan @mmdanggg2 

[log.txt](https://github.com/jmc2obj/j-mc-2-obj/files/5821217/log.txt)
[default.zip](https://github.com/jmc2obj/j-mc-2-obj/files/5821218/default.zip)

**Comment by mmdanggg2** [comment]
Thanks for that, I just put the new default.mtl in and I think there's some missing from it and the textsplit eg. crimson_trapdoor - I'll have a proper look tomorrow.
Not sure why it wouldn't work as long as you have the new blocks.conf

**Comment by mmdanggg2** [comment]
Ok, I found quite a few problems with the materials and some of the blocks so it ended up taking a while - wrote a [script](https://github.com/jmc2obj/j-mc-2-obj/blob/master/misc/CheckMtl.py) to cross-check.
I've renamed some of the old names to match what the textures are called now and fixed some blocks that were missing textures from 1.15 but I think it's done: fd4a71d67d4fe1f59f9976534c9b734d87398c90
Only block that is missing now is the jigsaw, bit of a complicated pattern of orientations so not done it yet.

**Comment by mmdanggg2** [comment]
Added the Jigsaw so I think it's done. Just want to update the mtl colours so they're not just all grey and I think I'll release.
Could you give it a go and make sure there's nothing obvious I've missed: 
[jMc2Obj-110Beta.zip](https://github.com/jmc2obj/j-mc-2-obj/files/5839471/jMc2Obj-110Beta.zip)

![image](https://user-images.githubusercontent.com/3161587/105112281-98dd7800-5aba-11eb-81af-13000ee9a71e.png)

**Comment by Zophiekat** [comment]
it works perfectly for me, 0 errors or missing textures!

**Comment by jacklynn-yan** [comment]
same, works for me as well! Thank you so much!

**Comment by mmdanggg2** [comment]
Alright I've put up [v110](https://github.com/jmc2obj/j-mc-2-obj/releases/tag/110) with a few other fixes. Thanks again for your help!
