### ISSUE TITLE
how to import the nether or the end

### ISSUE THREAD

**Issue by zainsajjad** [jmc2obj/j-mc-2-obj#145]
i wasnt able to find any totourial on this, i was just wondering if it was possible to import the nether or the end, if so can you tell me how?

**Comment by mmdanggg2** [comment]
You just set the dimension in the top right to -1 (Nether) or 1 (End)
Be aware that the nether has a solid bedrock roof so to be able to see into it you can lower the ceiling with the slider on the right.
![image](https://user-images.githubusercontent.com/3161587/105438982-efce8300-5c5b-11eb-80a3-1634108959cc.png)
