### ISSUE TITLE
Support for 1.17 new world generation

### ISSUE THREAD

**Issue by Zophiekat** [jmc2obj/j-mc-2-obj#147]
Newest snapshot brings changes to world generation.

- the build height has been risen from 255 to 320
- the build depth has been increased from 0 to -64
- while trying to import a 1.17 world it crashes the program

those are the main noticeable changes, not really sure what other background stuff is there

**Comment by jacklynn-yan** [comment]
I'd be happy to help with the new 1.17 blocks, but I don't know much about the new heights or world generation.

**Comment by Zophiekat** [comment]
[Trainguy](https://twitter.com/Trainguy9512) is actually making some really good progress on jmc2obj by himself, afaik he wants to get it fully working before making a commit here

**Comment by mmdanggg2** [comment]
Oh cool, that's good to know. I was going to wait until 1.17 released in case they changed the level format any more.

**Comment by MihinMUD** [comment]
1.17 blocks support?

and also grass_path is renamed to minecraft:dirt_path in 1.17

**Comment by mmdanggg2** [comment]
The proper extended height feature got moved to 1.18 which has just released and I just put v115 out which supports the 1.17 & 1.18 extended height worlds.
