### ISSUE TITLE
Stair UVs flipped the wrong way

### ISSUE THREAD

**Issue by Trainguy9512** [jmc2obj/j-mc-2-obj#149]
The top and bottom faces of stair models are flipped the wrong direction on Minecraft's Z axis, it's most noticable when stairs are next to solid blocks of the same material.
![image](https://user-images.githubusercontent.com/70923591/109043602-82b96d80-769f-11eb-8ef3-f368c2a08c89.png)
![image](https://user-images.githubusercontent.com/70923591/109043617-86e58b00-769f-11eb-8c5d-4726fd2b821d.png)
![image](https://user-images.githubusercontent.com/70923591/109043638-8baa3f00-769f-11eb-93cb-166d52e32449.png)

**Comment by mmdanggg2** [comment]
Thanks for reporting, this has been broken for a long time! New version with this fix and some others is up.
