### ISSUE TITLE
LowSize

### ISSUE THREAD

**Issue by mfantastic8** [jmc2obj/j-mc-2-obj#152]
How to make lowsize obj? Need export minecraft city into 4mb file.
![image](https://user-images.githubusercontent.com/33092889/111397247-82722800-86c9-11eb-8054-d05019573225.png)
idk how to reduce this points without deform UV

**Comment by mmdanggg2** [comment]
Best bet is to use the optimise mesh option when exporting. It merges neighbouring faces and can reduce the size quite a lot.
