### ISSUE TITLE
Some chunks render black on map and do not export

### ISSUE THREAD

**Issue by StevenStavrakis** [jmc2obj/j-mc-2-obj#153]
I imagine this is a known issue, however, I haven't seen any documentation on it. Some portions of the world outright don't appear on the map and attempts to export from those areas don't yield anything.

**Comment by mmdanggg2** [comment]
Are there any errors or messages in the log window?

**Comment by StevenStavrakis** [comment]
> 
> 
> Are there any errors or messages in the log window?

"Chunk is old version (pre 1.13), skipping!"

**Comment by mmdanggg2** [comment]
Well, there's your answer. You need to update those chunks to a newer version in minecraft. Just fly around to the areas you need.

**Comment by StevenStavrakis** [comment]
Yep, fixed. Not an issue I have in Mineways, but it works now.
