### ISSUE TITLE
Custom skulls

### ISSUE THREAD

**Issue by NJDaeger** [jmc2obj/j-mc-2-obj#156]
Hi, I work on a map that has a heavy use of custom heads (with plugins like https://www.spigotmc.org/resources/head-database.14280/ ). With that being said, whenever we plan on rendering our map, all heads are collected as a single material, while, in an ideal world, we would want the heads that have different textures to have different materials. If that alone could be accomplished, that would be fantastic- if it's not that much more work, however, it would also be nice if the heads could have the appropriate textures applied to them, as it would remove a step on our of writing a script to do it for us.  

The textures being applied isn't a necessity, but it would be a nice addition. The main thing I'm suggesting is for different heads to be associated with different materials. 

Thanks!

**Comment by mmdanggg2** [comment]
Yea, I think this can be done. I'm not sure about getting textures from mojang servers. Texture name would probably just be the player ids, not sure about how to convert ids to names. But they could probably be all unique materials at least.

**Comment by NJDaeger** [comment]
Thanks!

I know Chunky downloads the textures- you could theoretically reference their implementation of it if you felt up to that task. https://github.com/chunky-dev/chunky/blob/087b577ef899fbb5118cf04e5ffca77a50f2810a/chunky/src/java/se/llbit/chunky/block/Head.java 

Here is the player.dat reference as well https://minecraft.fandom.com/wiki/Player.dat_format/Player_Heads 

Hopefully those will help if you felt like doing the textures as well. Just having the materials will really help us out a ton, though!
