### ISSUE TITLE
Enabling "Create a separate object for each chunk" does not separate chunks

### ISSUE THREAD

**Issue by Zophiekat** [jmc2obj/j-mc-2-obj#157]
It simply doesn't, enabling or disabling other settings gives the same result, no chunk separation
![image](https://user-images.githubusercontent.com/47702767/116832620-4a407f00-ab7b-11eb-83fd-4e4566225d44.png)
![image](https://user-images.githubusercontent.com/47702767/116832623-51678d00-ab7b-11eb-937f-d10ffaa2f14e.png)

**Comment by Zophiekat** [comment]
nevermind, it was a Blender issue. the fix is to enable this checkbox
![image](https://user-images.githubusercontent.com/47702767/116833013-def7ac80-ab7c-11eb-9a56-5f104835d5c3.png)

**Comment by mmdanggg2** [comment]
Yep, it exports 'objects' into obj groups, that's the only one maya understands afaik.
