### ISSUE TITLE
Using 7-zip to open jmc2obj

### ISSUE THREAD

**Issue by Dai902831** [jmc2obj/j-mc-2-obj#159]
when i opened the jmc2obj file with 7 zip there were just other files and I don't know what to do now
![Screenshot (23)](https://user-images.githubusercontent.com/84243482/118372713-f709fb80-b580-11eb-8e6f-1b8f1ed48c07.png)

I don't know what file I have to open

**Comment by mmdanggg2** [comment]
You need to have java installed and run it with java
https://letmegooglethat.com/?q=how+to+open+jar+file
