### ISSUE TITLE
Support For 1.17 Blocks and Mobs

### ISSUE THREAD

**Issue by DivyanshByte** [jmc2obj/j-mc-2-obj#160]
Minecraft 1.17 Caves And Cliffs Part 1 is out. And If I Try To Import 1.17 World. There are No textures or models for the new blocks. So When The 1.17 Support will come?

**Comment by FXVictis** [comment]
@DivyanshByte i think it happend after optifine release. I too wait this.

**Comment by DivyanshByte** [comment]
Why Optifine is needed for jmc2Obj?

**Comment by FXVictis** [comment]
no, you misunderstood. I meant that support for worlds from 1.17 will be added after the release of OF, or after the release of the first patch (1.17. *)

there may be errors in the text, I used google translate

**Comment by DivyanshByte** [comment]
But My Question Why Can't We Import World Without OF release. Can't we use vanilla 1.17

**Comment by mmdanggg2** [comment]
Just released [Version 113](https://github.com/jmc2obj/j-mc-2-obj/releases/tag/113) which has support for all 1.17 blocks
