### ISSUE TITLE
You need to make a selection where all exported dimensions are >0.

### ISSUE THREAD

**Issue by ohisuckatthis** [jmc2obj/j-mc-2-obj#161]
<img width="539" alt="Screen Shot 2021-07-06 at 2 49 11 PM" src="https://user-images.githubusercontent.com/87043883/124670771-54c41100-de69-11eb-9015-38b2d41d2c29.png">
<img width="724" alt="Screen Shot 2021-07-06 at 2 49 33 PM" src="https://user-images.githubusercontent.com/87043883/124670821-61e10000-de69-11eb-8725-576995b665e4.png">
I am trying to export a rendering as an OBJ file from jmc2obj but I honestly don't know what I am doing, so every time I try to export the map as an obj file I get the error:

You need to make a selection where all exported dimensions are >0.

I don't know what this means or what I'm doing wrong.

**Comment by mmdanggg2** [comment]
Did you actually select the area to export? Just click and drag.
![image](https://user-images.githubusercontent.com/3161587/124671327-37b13180-dead-11eb-91cc-5c434f28a2f8.png)

**Comment by ohisuckatthis** [comment]
I was so focused on other things I didn't realize I had to do this. Thanks!

**Comment by ohisuckatthis** [comment]
Thanks, I didn't even realize I had to drag because I was focused on the error.
