### ISSUE TITLE
Unable to grab banner and custom head textures if upgraded from 1.12.2 world to 1.16.5

### ISSUE THREAD

**Issue by Coppertine** [jmc2obj/j-mc-2-obj#163]
I am attempting to do some renders with banners (all craftable in the loom) and custom heads. However, these are upgraded from the 1.12.2 world to 1.16.5.

Currently, all banners and heads look like below which would indicate that it never downloaded any of the custom heads nor created any banner images.
![image](https://user-images.githubusercontent.com/37494321/127799538-13ef9c1b-6ed7-4045-988f-60a7feb1f71d.png)

Additional Info and downloads:
jmc2obj version: b93ef97 (Built using InteliJ Idea)
World (1.16.5): [Schematic World.zip](https://github.com/jmc2obj/j-mc-2-obj/files/6914151/Schematic.World.zip)
.blend (Includes two scenes, 1 for MCPrep import and 1 for Blender .obj import, all files are embedded into .blend): https://drive.google.com/file/d/1Dm3BzHWVuM4hygNtK3V9E4bW5Om2KOAZ/view?usp=sharing
obj and tex files: https://drive.google.com/file/d/1Wbpc9MpP5O4gIOA0esIuqe5i55T3wGao/view?usp=sharing

**Comment by mmdanggg2** [comment]
I think this happened because you tried to export without exporting textures first. The program gets stuck and wont try to export those banners/heads again until a you restart it. I'll fix it so it can try again if it failed to export them.

**Comment by Coppertine** [comment]
As a note, all textures were exported first before the obj was exported.

**Comment by mmdanggg2** [comment]
Was there any errors in the console log window? The export works fine for me.

**Comment by Coppertine** [comment]
It works perfectly! Thank you!

**Comment by Coppertine** [comment]
Although, the only issue is that both layers of the player head aren't rendered. Is this intended for only the bottom layer to be exported? I'm fine with swapping out all of the heads with their correct counterparts manually.

**Comment by Coppertine** [comment]
![image](https://user-images.githubusercontent.com/37494321/127942928-e6017ece-32fe-4021-b589-2535be439ab7.png)
Just to show an example, the P is intended to be displayed here.

**Comment by mmdanggg2** [comment]
Yes, that is a known limitation at the moment. I'm working on a big model/texture update so I might fix it after I'm done with that.
