### ISSUE TITLE
Feature Request: Allow programmer art resource pack as an option when exporting.

### ISSUE THREAD

**Issue by Coppertine** [jmc2obj/j-mc-2-obj#164]
I want to be able to view a 1.12.2 world as a 1.12.2 world, but due to how jmc2obj only reads 1.13 worlds, I have to load it in 1.16 then export through there. It would be best that since only 1.12.2 blocks were used to allow the user to use the Programmer Art for the older style builds and not have to use the new 1.13 textures.
This could be a check box in the export panel in the "Texture export" section.
Currently, it is hard to find the programmer art resource pack to use as the custom resource pack. So this would make rendering in 1.12.2 easier.

**Comment by mmdanggg2** [comment]
Ok I've had a quick look into this and the Programmer Art resource pack is just a normal resource pack .zip but it's automatically downloaded and added to the list by minecraft.
You just need to use it in jmc2obj the same as any other resource pack.
Problem is the file is hidden and obscured when minecraft downloads it in the .minecraft\assets\objects\## folders so you'll have go through the indexes to find it there, download it from somewhere else or use something like this [Programmer Art Fix](https://www.curseforge.com/minecraft/texture-packs/programmer-art-fix)

**Comment by Coppertine** [comment]
Thank you for your help, however, the provided link is intended to be used ontop of the Programmer Art pack.

**Comment by mmdanggg2** [comment]
So just go into the .minecraft\assets folder and get the file from there. The json files in indexes tell you what the name is:
![image](https://user-images.githubusercontent.com/3161587/127942258-33afa363-8719-4d46-9516-065bb021f8c0.png)
then just copy the file and rename it to programmer_art.zip
![image](https://user-images.githubusercontent.com/3161587/127942437-0906072c-e218-416f-85bd-f33ec9a8bd58.png)

**Comment by Coppertine** [comment]
Thank you for your help, I already got the thing running.
