### ISSUE TITLE
[Feature] Export armor stands

### ISSUE THREAD

**Issue by XilefTech** [jmc2obj/j-mc-2-obj#165]
I have tried exporting a map with a lot of armor stand art but I noticed that jmc2obj did not export a single one of them.

Would be cool if it could fully export armor stands with their armor, possibly player heads, and their tools if they're spawned showing arms. This should also include invisible armor stands / the equipment they hold.

_(the map I was trying to export was 1.16.5 btw)_

**Comment by mmdanggg2** [comment]
I think armor stand export was working, I haven't looked at entity export in a long time. Seems like 1.17 moved them to a new file so that will need to be fixed. You did enable entity export?

**Comment by XilefTech** [comment]
Yes I did enable entity export. And the map was 1.16.5 so it probably wasn't due to changes in 1.17

**Comment by mmdanggg2** [comment]
Entity exports were totally broken, probably has been for a long time. Fixed it here: f883977df99e96b19d830f036aff291877592d3a
There's not a lot of entities supported but basic armour stands work. It'll be in the next update when I manage to finish it up.
