### ISSUE TITLE
MCprep Alpha not working

### ISSUE THREAD

**Issue by Tiefseetauchner** [jmc2obj/j-mc-2-obj#169]
Coming from https://github.com/TheDuckCow/MCprep/issues/246
It seems that MCprep messes up the Alpha when using v113
![image](https://user-images.githubusercontent.com/48085877/136671625-3f4032a9-16b0-4764-b7f9-66c837629050.png)
This does not occur with 112, thus it seems to be a JMC2OBJ thing (as discussed in the issue above)
Are there any ideas why this could be happening? Anyone else even had this issue or is it just me?

**Comment by mmdanggg2** [comment]
I think this is fixed in MCprep now
