### ISSUE TITLE
Entity Positions Wrong

### ISSUE THREAD

**Issue by jongames** [jmc2obj/j-mc-2-obj#170]
When selecting 'render entities', the model has extra entities included which are not within the boundaries selected (where all the blocks stop in the render of the model).  

Here is an example: 
![image](https://user-images.githubusercontent.com/18472148/136733814-9e1f012a-f102-4725-a5d7-0afb2e997c2f.png)

Switching the options around does not help it seems.  I tried turning off and on various other options and nothing seems to affect this behavior.

**Comment by mmdanggg2** [comment]
It was exporting all entities in a chunk if any part of the chunk was exported. Now it will check the positions of the entities before exporting them.
