### ISSUE TITLE
Typo in Banner definition.

### ISSUE THREAD

**Issue by Coppertine** [jmc2obj/j-mc-2-obj#172]
![image](https://user-images.githubusercontent.com/37494321/137107661-e4c8a273-bdfa-4aeb-ae98-22f54c380e72.png)
https://github.com/jmc2obj/j-mc-2-obj/blob/0892c5b48b3f8dbe2cd018811bcb0b897135a253/conf/textures.json#L53
Basically this..

**Comment by mmdanggg2** [comment]
Thanks for reporting.
It can handle over 6 layers no problem. It failed because it contained a vhr layer which it failed to get the texture for.
