### ISSUE TITLE
Unable to open obj

### ISSUE THREAD

**Issue by freshbread28** [jmc2obj/j-mc-2-obj#174]
The problem is that when I throw obj from jmc 2, this error comes out. Help what to do? 
![image](https://user-images.githubusercontent.com/93883288/140659684-cad844d4-fb42-48c6-8278-8d13c6048730.png)

**Comment by mmdanggg2** [comment]
Hmm, that's a weird one. Can you send a small obj that has this problem?

**Comment by freshbread28** [comment]
> Hmm, that's a weird one. Can you send a small obj that has this problem?



> Hmm, that's a weird one. Can you send a small obj that has this problem?
https://drive.google.com/drive/folders/19KjcM_WWtPcApl_ggtnXFu_d9SE3CdoV?usp=sharing 

I hope you can help. There is simply no better program. I'm afraid that my whole project will close because of this

**Comment by freshbread28** [comment]
And then I will close the question, I hope it will help you somehow)

**Comment by freshbread28** [comment]
https://drive.google.com/drive/folders/19KjcM_WWtPcApl_ggtnXFu_d9SE3CdoV?usp=sharing as I understand it, it can't import any blocks

**Comment by freshbread28** [comment]
> Hmm, that's a weird one. Can you send a small obj that has this problem?

https://drive.google.com/drive/folders/19KjcM_WWtPcApl_ggtnXFu_d9SE3CdoV?usp=sharing as I understand it, it can't import any blocks

**Comment by freshbread28** [comment]
> Hmm, that's a weird one. Can you send a small obj that has this problem?

help pls

**Comment by mmdanggg2** [comment]
This is a bug in blender on Windows. You just need to save your file with latin/ascii characters in the name rather than Cyrillic.

**Comment by freshbread28** [comment]
thank you so much, I'm just from Russia and I couldn't even imagine this)

> This is a bug in blender on Windows. You just need to save your file with latin/ascii characters in the name rather than Cyrillic.

**Comment by mmdanggg2** [comment]
FYI this looks like the bug in the blender tracker: https://developer.blender.org/T86783
