### ISSUE TITLE
Missing block faces with modded blocks

### ISSUE THREAD

**Issue by PixusPanic** [jmc2obj/j-mc-2-obj#178]
Hey; I've been toying around with the latest update to jMc2Obj and I will say that I'm very surprised and impressed that modded block support has been added. It's something I've always wanted to see, and here we are.

I wanted to give out a quick bug report or suggestion, namely that the modded blocks (in this case, [MrCrayfish's Furniture Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod) and [XK's Deco](https://www.curseforge.com/minecraft/mc-mods/xks-decoration)) I've been using always seem to cull the faces below and besides them, regardless if they're not a full block or not. From a programming point of view, I think I get what is happening because the program isn't able to read the block models, so it doesn't know they're not full blocks, but I could be wrong. A way for the program to automate culling for this would be appreciated.
![Render](https://user-images.githubusercontent.com/68515252/143768717-6560c1b7-b091-4fb2-91c5-a833d0748425.png)

**Comment by mmdanggg2** [comment]
Currently it defaults to blocks being solid so any unknown blocks will occlude neighbouring blocks. Take a look at the blocks.conf file, at the moment you need to add the modded blocks in there to override the block properties. The console log should tell you which block ids couldn't be found in the conf file. I might end up switching it so the default is to not occlude, I think more blocks are like that in base minecraft anyway.

**Comment by PixusPanic** [comment]
Thanks for your detailed response! I did take a look in there and I wasn't aware the console says which blocks couldn't be found in it, but that'll prove to be useful.
Do you have a guide for adding in new blocks to it?

**Comment by mmdanggg2** [comment]
There isn't a guide but it's pretty simple, just copy an existing entry and add it to the end with the new blocks id.
eg. 
```
	<block id="crayfish:table" name="Table">
		<occlusion>none</occlusion>
	</block>
```
Just change the id to the new blocks' id. The name doesn't really matter, it's only used in the block selection menu.

**Comment by PixusPanic** [comment]
Sorry for my late response, but thanks!
Just a suggestion, although the ability to support additional config files (like for example, one configuration file contains vanilla assets, another has just modded assets from a single mod) would be appreciated.

**Comment by mmdanggg2** [comment]
That's a good idea, that could be great for making and sharing mod block configs.

**Comment by mmdanggg2** [comment]
It will now look for any files matching blocks-*.conf in the conf folder and add those definitions.
As a super simple example, here is one for the couple of blocks in my doge mod:
blocks-doge.conf
```xml
<?xml version="1.0"?>
<blocks>
	<block id="doge:mining_rig" name="Mining Rig"></block>
	<block id="doge:doge_block" name="Doge Block"></block>
</blocks>
```
