### ISSUE TITLE
File OBJ Does not open in any program? help!!

### ISSUE THREAD

**Issue by SirjoAudi** [jmc2obj/j-mc-2-obj#181]
Hello Friends! The Obj file saved from the jMc2Obj 115 program does not open the 3d object, the scene is empty, only the coordinates are visible, but only the materials open perfectly with transparency in Cinima4D! I suffer for a week.
How it was! At first, of course, I exported and tried to open the files in Blender 2.9.3, I have MCprep there, but when importing the scene into the blender after loading, the scene was empty and all objects appeared in the window from the right and only one coordinates appeared in the blender preview window!? Screenshots are attached.

This is a link to non-working files
https://drive.google.com/drive/folders/1lexyugrJrx4Acahq3iSUC-qS9zue3JmG?usp=sharing

This is a link to a file that I accidentally saved with some settings and they are Working!
https://drive.google.com/drive/folders/1p20z6nk6_3pdxiMD4zfzzhf3kckF3tzN?usp=sharing

When I saved a lot of test folders for the blender with obj files and nothing worked out for me, I tried to open from the exports created by one of the first files in the cinema 4d program and, lo and behold, about four files open perfectly, the scene and materials!!! BUT it's too early to rejoice, all the other hundreds of test renderers from jMc2Obj 115 to the obj file do not open in any program. And now I do not know what the reason is why only in one folder the files were saved by workers from the program jMc2Obj 115 hundreds of subsequent attempts with different settings only materials are opened and the scene is empty only coordinates!?
Screenshots and one file that does not open, and I have hundreds of them attached. I also want to add a few working files that I got by accident, I already think so.

And one more thing, in the viewing window of the jMc2Obj program after pressing Load. Loading occurs only from saving Minecraft versions from 1.14 to 1.16. and saving versions 1.11 - 1.12 after pressing LOAD in the jMc2Obj program, the screen is black and nothing is visible.

**Comment by mmdanggg2** [comment]
Looks like your scale is at 0 so it is just scaling all the vertices to a single point.
![image](https://user-images.githubusercontent.com/3161587/146978007-df688c21-42cd-4286-b206-f2c4af0bee1e.png)
Just set it back to 1

**Comment by SirjoAudi** [comment]
Thank you very much.  now when there is 1 everything opens, thank you for your help :)
