### ISSUE TITLE
water internal faces, and different shaped exports.

### ISSUE THREAD

**Issue by bokonon-bokonon** [jmc2obj/j-mc-2-obj#190]
Hi there,

First up, thanks for providing this great tool.

I have two questions, regarding the command line application.

1:  Is there a way to render water with internal faces, like how rock renders when using the `--object-per-block` flag?
<img width="400" alt="Screen Shot 2022-05-13 at 12 08 01 AM" src="https://user-images.githubusercontent.com/103638195/168073572-cda983c0-c052-4229-b60b-36371e24dcfe.png">

2: Is there any way to render a more complex shape, like a circle, or other arbitrary bounds? Cropping the land, so to speak. 
![_168072600-1f472371-cf6d-44af-849d-fa0453f95af4](https://user-images.githubusercontent.com/103638195/168073868-84e65571-861d-4edb-aada-97cab89db8b5.png)

Thank you!

**Comment by mmdanggg2** [comment]
I think for the more complex export region we'll leave that discussion to #72
The water probably should be exporting all the block edges when doing per block export, that looks like it's broken at the moment so I'll see if it can be fixed.

**Comment by bokonon-bokonon** [comment]
I just build current master and tested, and the water --object-per-block works as expected. Thanks so much @mmdanggg2 for the speedy fix.
