### ISSUE TITLE
Height map

### ISSUE THREAD

**Issue by danijel3** [jmc2obj/j-mc-2-obj#192]
This looks like it should refer to "gh" instead of "gb", right?

https://github.com/jmc2obj/j-mc-2-obj/blob/fd07b6360aebec7d610862f9ca52c6717a26c066/src/org/jmc/Chunk.java#L538

**Comment by mmdanggg2** [comment]
Huh, yea. always wondered why empty border chunks looked like they were at full height.
![image](https://user-images.githubusercontent.com/3161587/169586479-c51fb85e-abd0-4f20-8cef-5a2a19d1a03b.png)
Fixed:
![image](https://user-images.githubusercontent.com/3161587/169586542-6d254077-8b00-40ba-a63f-4aa79defc0b0.png)

Not sure if I like the white though.

**Comment by mmdanggg2** [comment]
So the height thing was actually something else, but I think I'll keep it black as that makes the most sense:
![image](https://user-images.githubusercontent.com/3161587/169623799-0c8a82e0-4496-4881-b0d8-962ad7814790.png)
