### ISSUE TITLE
there is no button to export texture 

### ISSUE THREAD

**Issue by CodeCraftPlugin** [jmc2obj/j-mc-2-obj#193]
So I was watching tutorials on  making Minecraft animation and the youtube exports the texture and there is no option for me to export the texture 

![image](https://user-images.githubusercontent.com/86466022/172117048-b7a5fa8a-72fc-46fd-8a58-5a8e61a2513f.png)
![export](https://user-images.githubusercontent.com/86466022/172117659-86aed921-72a6-40d2-b225-8825df0142e1.png)

Please Fix it If this is a issue

**Comment by mmdanggg2** [comment]
The tutorials are out of date, that is the option. If it is on, textures will be exported when you export the obj.

**Comment by CodeCraftPlugin** [comment]
thanks for the help
