### ISSUE TITLE
Stairs get exported with nonmanifold geometry

### ISSUE THREAD

**Issue by TheoBearDB** [jmc2obj/j-mc-2-obj#196]
I noticed this after attempting to add subsurface scattering to some stairs in Blender. SSS in Blender is very picky when it comes to geometry, and if I plug it in to my textures and render, this is what the blocks look like out of the gate:

![image](https://user-images.githubusercontent.com/97541479/184516199-b6a7bb02-7e12-4d21-baa5-4bf7221f6fe8.png)

The black lines are from internal faces inside the stairs. I've tried many different options in trying to get the block to not have those internal faces, but nothing I try has worked. Also, tools in Blender such as "Select interior faces" or "select nonmanifold edges" don't select the right things either. I think I identified what was going on though. 

![image](https://user-images.githubusercontent.com/97541479/184519161-f8281281-3897-4425-a40b-936c5f5b866f.png)

Checking the face underneath the top part of the stair, there is just one face underneath it without any other edges and this makes the program pretty hard to recognize the internal faces it seems. Is this something that can be changed?

**Comment by mmdanggg2** [comment]
Yes, this is an unfortunate side effect of using the in game models from resource packs. Very difficult to detect this kind of thing and fix it. The old hardcoded stair model code should still work though and doesn't have this problem, removes all the faces between stair blocks and no inside geo. All you have to do it edit your blocks.conf to change back to the old definitions, you can find them here: https://github.com/jmc2obj/j-mc-2-obj/blob/a8344c692ca8cd4347446d10af7281ca143ce7fd/conf/blocks.conf#L689-L869 Slabs are also better optimised using the old code, but of course they wont change if you have a resource pack with custom models for them.

**Comment by TheoBearDB** [comment]
Once again @mmdanggg2 you save me a crap ton of headache. Thanks so much, this worked like a charm! Just a little bit of things to edit, but far far less work on my part! 

Now that I'm here though, I notice that fences have this issue too. Is there a model of fence that doesn't have ton of internal geometry, or some occlusion method I can use to help?

**Comment by mmdanggg2** [comment]
The old Fence model might be a little bit better but it doesn't remove the faces between fences like the stairs. You'd have to try and make your own model to add that level of optimisation.
