### ISSUE TITLE
Default MC Textures don't load [Using LTS on MAC OS]

### ISSUE THREAD

**Issue by diversifiedplayz** [jmc2obj/j-mc-2-obj#197]
<img width="1665" alt="Screenshot 2022-08-18 at 8 34 22 PM" src="https://user-images.githubusercontent.com/76275611/185429138-8ffa38a8-6e95-4037-b755-8cdde2067030.png">

**Comment by diversifiedplayz** [comment]
when I export, here is the error I ge
<img width="1455" alt="Screenshot 2022-08-18 at 8 38 44 PM" src="https://user-images.githubusercontent.com/76275611/185429957-7484dc3d-7c6e-4483-b833-e787c5a8f048.png">
t

**Comment by mmdanggg2** [comment]
I guess it can't find your .minecraft folder with the Minecraft .jar file in it. You have Minecraft Java latest version installed?

**Comment by diversifiedplayz** [comment]
Thanks I started 1.19.2 and it was back to normal, strange because I already had 1.19.2 installed but used fabric for my projects
