### ISSUE TITLE
Reuse exported meshes in Unity

### ISSUE THREAD

**Issue by FishWoWater** [jmc2obj/j-mc-2-obj#198]
Hi! Thanks for your efforts in this excellent project! 

I have exported meshes successfully, but it seems that it's difficult to reuse them as materials in Unity 

No matter I export them as a single object, or separated objects by chunks, or separated objects by materials, a reasonable `box_collider` in Unity can not be clearly defined (since such practice violates the physical structure in real world). 

![image](https://user-images.githubusercontent.com/37951601/188273427-09d20550-08d1-48f7-9121-04ba6b452d7e.png)

Separated objects by blocks might help but will destroy the RAM

Is this any option that might solve this problem? 

Thanks in advance

**Comment by mmdanggg2** [comment]
Hey, unfortunately I don't think there is much that jmc can do to help with this problem. My only suggestion is if Unity has an option like `Use Complex Collision As Simple` in Unreal where it can just use the mesh polygons as the colision for the object.

**Comment by FishWoWater** [comment]
> Hey, unfortunately I don't think there is much that jmc can do to help with this problem. My only suggestion is if Unity has an option like `Use Complex Collision As Simple` in Unreal where it can just use the mesh polygons as the colision for the object.

Thanks for your suggestion, I can have a try :)
