### ISSUE TITLE
issue with loading textures

### ISSUE THREAD

**Issue by ghost** [jmc2obj/j-mc-2-obj#199]
I am having trouble getting textures to work in the latest version of j-mc-2-obj.

I use the Linux Flatpak version of the PolyMC launcher (a fork of MultiMC) so my Minecraft is not installed in the normal directory. So j-mc-2-obj cannot extract textures from the Minecraft directory.

i get errors like this in the console log:

```
ERROR: Couldn't find assets/minecraft/textures/dirt_grass_top.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/water.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/leaves_oak.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/stone.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/dirt.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/diorite.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/gravel.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/sand.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/coal_ore.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/granite.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/leaves_birch.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/andesite.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/snow.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/iron_ore.png in current resource packs
```

and everything appears pink. I have tried the following to load textures manually:

- [x] Added 1.19 client jar to the resource packs in settings
- [x] Same as above but also tried the 1.18 jar, 1.16 jar, 1.15 jar, 1.13 jar, 1.12 jar
- [x] Added a resource pack ZIP provided by Mine-imator that contains the vanilla texures.
- [x] Made my own resource pack ZIP file where i copied the assets from the minecraft 1.19 jar `assets/minecraft/textures/block/` into the zip at `assets/minecraft/textures/`

After doing that last one in the list, most texures do seem to load. i can see the stone and dirt and snow in the world now but i still dont see grass. and i still have these errors in the console.

```
ERROR: Couldn't find assets/minecraft/textures/dirt_grass_top.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/water.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/leaves_oak.png in current resource packs
ERROR: Couldn't find assets/minecraft/textures/leaves_birch.png in current resource packs
ERROR: Couldn't find blockstate minecraft:honeycomb_block in any resource pack!
Found unknown block id: minecraft:honeycomb_block
ERROR: Couldn't find assets/minecraft/textures/leaves_spruce.png in current resource packs
ERROR: Couldn't find blockstate minecraft:honey_block in any resource pack!
Found unknown block id: minecraft:honey_block
ERROR: Couldn't find blockstate minecraft:beehive in any resource pack!
Found unknown block id: minecraft:beehive
```

maybe the issue is the file names. because its called `grass_block_top.png` in the minecraft assets and j-mc-2-obj is looking for `dirt_grass_top.png`

couldn't find any documentation so i figured i'd ask how to do this. do i have to rename `grass_block_top.png` to `dirt_grass_top.png` and do the same for the other textures that it still cannot find? i tried renaming the grass top and now that texture does load but it's grey because it doesn't have the green biome tinting. Would i have to tint the grass myself as well?

**Comment by mmdanggg2** [comment]
That sounds like it's trying to use old texture files, it also mentions that it doesn't know about the honey and beehive blocks. Could you have an old blocks.conf file where you installed jmc? Try deleting the conf folder to make sure it's using the latest one.
If your minecraft is not installed in the standard location, adding the client (1.19.jar) to resource packs is the right way to do it.
