### ISSUE TITLE
Bells not being exported

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#202]
In my scene, most blocks are good, except for the bell, which is not exported for some reason.

Material preview (also the same thing in rendered view):
<img width="145" alt="image" src="https://user-images.githubusercontent.com/50642934/198352729-18316475-54f0-45e7-a6b3-9cc0d5d1f5ee.png">

Using the latest version of jMc2Obj on a 1.19.2 world.

**Comment by mmdanggg2** [comment]
The bells are a bit weird, they are actually block entities so you need to enable entity export to see them.

**Comment by Macintosh-Fan** [comment]
Been a while since I paid attention to this, but yeah. Any plans to make it a block in the future, since it sorta is, @mmdanggg2?

**Comment by michal212345** [comment]
Download the latest build from actions, it works perfectly @Macintosh-Fan
