### ISSUE TITLE
Ui glitching

### ISSUE THREAD

**Issue by vidhaanyadav** [jmc2obj/j-mc-2-obj#205]
When i open the software the Ui starts going crazy, everything starts moving around and glitching.
error:
![image](https://user-images.githubusercontent.com/67150368/210162869-c2e3f178-ad75-4315-bbad-baf8947734ef.png)

the glitchy ui:
![image](https://user-images.githubusercontent.com/67150368/210162896-5277a57f-bc3d-4d84-8706-d12cf5d968fd.png)
It's kind of hard to see in the image but everything was moving crazy fast across the screen

**Comment by michal212345** [comment]
Could you elaborate?

What version of JMC are you using,
What system/os you have,
Could you send the full logs?
And could you gif the issue?

**Comment by mmdanggg2** [comment]
Can't reproduce, need more info.
