### ISSUE TITLE
Latest JAR thinks it's version 119, not 120

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#208]
When I run the latest JAR, it thinks it is the older version.
```
macintoshfan@MacintoshFan Downloads % java -jar jMc2Obj-119.jar
jmc2obj 119
```

<img width="96" alt="image" src="https://user-images.githubusercontent.com/50642934/213937605-00e388cd-add3-4fb2-a492-1e3e8d0ef06d.png">

**Comment by mmdanggg2** [comment]
Ah, nice catch. Thanks! Updated the file on the release page.
