### ISSUE TITLE
Powder snow not rendering properly

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#211]
Using the latest version of Jmc2Obj (120), and using the latest version of Minecraft (1.19.3).

<img width="942" alt="image" src="https://user-images.githubusercontent.com/50642934/218284291-46dbdf67-330f-44c6-8b50-48f033bbd662.png">

**Comment by Macintosh-Fan** [comment]
It appears just fine in material preview in Blender, but not in rendered view.
<img width="516" alt="image" src="https://user-images.githubusercontent.com/50642934/218284576-cd9e8d1b-f6ef-4421-80ac-d1ce63470fbc.png">

**Comment by mmdanggg2** [comment]
Seeing that too, being caused by the powdered snow model exporting 2 faces on top of eachother.

**Comment by Macintosh-Fan** [comment]
> Seeing that too, being caused by the powdered snow model exporting 2 faces on top of eachother.

So, sorta like a duplicate mesh?
