### ISSUE TITLE
[Suggestion] Allow textures to be fully wrapped around

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#212]
So I don't have a problem like this when I want to hide snow...
<img width="691" alt="image" src="https://user-images.githubusercontent.com/50642934/218284470-b9b476cb-f11b-4c6f-b92a-adc76be6ff0c.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/50642934/218284487-7e1c3619-f3a5-4ced-890a-ac7d85c1ce39.png">

**Comment by mmdanggg2** [comment]
I believe if using separate object per material without enabling occlude adjacent materials will do what you want

**Comment by Macintosh-Fan** [comment]
Yep. One of those English words I didn't know...

Thank you!

**Comment by Macintosh-Fan** [comment]
Though, what about selecting specific blocks to allow occlusion; in my case on the image above, just snow, @mmdanggg2?

**Comment by mmdanggg2** [comment]
For your case I would suggest maybe doing 2 exports, one with everything but the snow and then another with only the snow, then it's totally separated.
