### ISSUE TITLE
1.20 jmc-2-obj export problem

### ISSUE THREAD

**Issue by Fexiqo** [jmc2obj/j-mc-2-obj#213]
so recentely i got this error when exporting  

 ERROR: Cannot write to the chosen location!
java.io.IOException: Access is denied
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at org.jmc.ObjExporter.export(ObjExporter.java:66)
	at org.jmc.gui.ExportWindow$8$1$1.run(ExportWindow.java:748)
	at java.lang.Thread.run(Unknown Source)

due to this error i cant export anything .Is there any way i can fix this ?

**Comment by mmdanggg2** [comment]
jmc can't write to the directory you've picked to export the obj to, you need to make sure you have permissions or try a different location.

**Comment by Fexiqo** [comment]
how can i make sure i have permission and like how to get permission ? Also diffrent location didnt work

**Comment by mmdanggg2** [comment]
You should usually have "full control" of anything in your user folder, desktop for eg. You can check in folder properties:
![image](https://user-images.githubusercontent.com/3161587/220403550-d914e124-6802-4146-923e-1140f48ce67e.png)

**Comment by Fexiqo** [comment]
well i checked  every jmc  and blender related folder and i had allowed full control . Also i tried other versions   and creating new folders to export to.And all the time the same error appear
