### ISSUE TITLE
Vegetation not rendering properly

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#214]
Appears fine in material preview in Blender, but not in rendered view.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/50642934/222524235-4564ba2e-1de8-46e8-8d70-b589913252fc.png">
<img width="705" alt="image" src="https://user-images.githubusercontent.com/50642934/222524136-e774f378-ed88-4f88-a9bd-9f32253b2e3d.png">

**Comment by mmdanggg2** [comment]
I think this is essentially the same issue as #211 there are 2 faces in the same position facing opposite directions.
![image](https://user-images.githubusercontent.com/3161587/222974488-c39a4679-5625-480e-91c1-c1dcc8e316bf.png)
Fine for the game when it has backface culling enabled but not so great for offline renderers. Weirdly it seems fine on gpu for me but these shouldn't be exported ideally.

**Comment by Macintosh-Fan** [comment]
I'll also point out that this is an issue for lily pads as well.

**Comment by Macintosh-Fan** [comment]
Great! Just wondering @mmdanggg2, when will the next release be with these fixes?

**Comment by mmdanggg2** [comment]
Not sure when i'll put it out, maybe next week. You can always try the latest changes [from here](https://github.com/jmc2obj/j-mc-2-obj/actions/workflows/maven.yml), just download the jar file artefact of the latest commit.

**Comment by Macintosh-Fan** [comment]
@mmdanggg2, I'm still getting some issues with it. Though, this might be for 1.12.2 (I got the Hypixel lobby world file), so it could be a version restriction, but not too sure...

<img width="618" alt="image" src="https://user-images.githubusercontent.com/50642934/234695478-01eca45f-6274-424d-bb96-8ced3a98d2f6.png">

Also, in the world, it seems like it's only wheat that is affected.

**Comment by Macintosh-Fan** [comment]
UPDATE: it seems like I forgot to disable this: 
<img width="354" alt="image" src="https://user-images.githubusercontent.com/50642934/234719991-2a9e09e6-6f97-4bfb-a114-c933d511c26a.png">


However, it is still weird at certain angles...
<img width="625" alt="image" src="https://user-images.githubusercontent.com/50642934/234720091-61bcf4f9-012f-4e71-8505-3bfd6c047638.png">
<img width="516" alt="image" src="https://user-images.githubusercontent.com/50642934/234720104-b55c4955-8ce8-4536-a047-24b6b5cc92de.png">

Blender file (make sure to have sun position enabled):
[file.blend.zip](https://github.com/jmc2obj/j-mc-2-obj/files/11337924/file.blend.zip)
World file:
[test.obj.zip](https://github.com/jmc2obj/j-mc-2-obj/files/11337925/test.obj.zip)

**Comment by mmdanggg2** [comment]
That is due to not having enough transparency bounces in your cycles settings.

**Comment by Macintosh-Fan** [comment]
<img width="613" alt="Screenshot 2023-05-21 at 11 47 29 AM" src="https://github.com/jmc2obj/j-mc-2-obj/assets/50642934/a67d06b7-4518-4f00-b929-711fc8c7acec">

A little unsure if it is similar to this issue, but when I want to change Minecraft's glass into the Blender glass material, there are these weird lines across it.
