### ISSUE TITLE
Cant see exported things jMc.20.obj

### ISSUE THREAD

**Issue by Fexiqo** [jmc2obj/j-mc-2-obj#216]
![Zrzut ekranu (258)](https://user-images.githubusercontent.com/125993815/224540282-20646b09-ba3a-44e4-9cc0-1cb94ec0c326.png)

Soo like 3 weeks ago i send help request about that i coudnt export .Welll SOMEHOW i figured out how to fix this(i still dont know how i did that).Also i fixed the configuration file problem by creating file named conf and putting it in blender folder.But some minutes after i fixed it the other problem appeard i cant see exported things.well atleast i can export now but still . How can i fix this .

**Comment by mmdanggg2** [comment]
Most likely you just have not moved your viewport to where the model is, they are exported to the same coordinates as the blocks are in game. Select one of the models and go view -> frame selected. Or you can export with the offset set to center, then the model will be centred around 0,0,0
