### ISSUE TITLE
Disable chunk rendering during export

### ISSUE THREAD

**Issue by Cryptite** [jmc2obj/j-mc-2-obj#221]
As they compete with cpu resources, it seems like it'd be a better performance change to pause/stop/clear the viewport of any active chunk drawing that is going on when exporting. Exports go quicker if you have no chunk drawing going on (I zoom into the ocean very closely, for example, to be sure it's done drawing before exporting).

**Comment by mmdanggg2** [comment]
Thanks for the suggestion!
