### ISSUE TITLE
UI Behaving erratically

### ISSUE THREAD

**Issue by icytower387** [jmc2obj/j-mc-2-obj#224]
video of issue: https://github.com/jmc2obj/j-mc-2-obj/assets/40437007/3c678ae1-be27-4f21-9547-cacccfe07f73

i've tried older versions and whatnot but the issue persists, maybe it only affects certain hardware? tried running as admin etc
using java 19

**Comment by mmdanggg2** [comment]
That's pretty bad, the fact it's affecting the file picker too means it's almost certainly not an issue with jmc. More likely to be an issue with other software on your machine, my first guess would be java itself or graphics drivers. Do you have the same issue with other java apps?
