### ISSUE TITLE
Missing Textures 

### ISSUE THREAD

**Issue by 4nyNoob** [jmc2obj/j-mc-2-obj#230]
I'm using openjdk 17 on nobara 38

![image](https://github.com/jmc2obj/j-mc-2-obj/assets/113947854/d89f686c-5fc6-4d03-a993-6d4181b394b5)

looks like jmc doesn't want to use the resourcepack even if it's a zip or extracted

**Comment by mmdanggg2** [comment]
Is the latest Minecraft installed in the usual `~/.minecraft` dir? If it is, make sure you have use latest minecraft found as default in the resource pack settings. If it's not, you need to add the Minecraft 1.20.1.jar as a resource pack to use the base games files.

**Comment by 4nyNoob** [comment]
oh yea, the jar works, thank you so much
