### ISSUE TITLE
Texture export throws errors on larger regions, yet clicking ok exports it fine

### ISSUE THREAD

**Issue by Privatech38** [jmc2obj/j-mc-2-obj#233]
When I export larger regions from my world, this erorr shows:
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/99482159/289f5379-dbb2-4577-8244-1a76b2dd1f91)
Together with console throwing the error message:
```ERROR: Couldn't export texture minecraft:block/blackstone
javax.imageio.IIOException: Can't create an ImageOutputStream!
	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1553)
	at org.jmc.TextureExporter.exportTextures(TextureExporter.java:159)
	at org.jmc.ObjExporter.export(ObjExporter.java:382)
	at org.jmc.gui.ExportWindow.lambda$runExport$0(ExportWindow.java:885)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Clicking ok on every pop-up error window seems to make it work and textures get exported as expected.

Not clicking ok and closing the program causes missing textures.

It's worth noting the actual region being exported was imported via WorldEdit schematics on a paper 1.18.2 server.
I import the exported MTL and OBJ via the [MCPrep project by TheDuckCow](https://github.com/Moo-Ack-Productions/MCprep) to Blender and it works perfectly fine.

jmc2obj version: 122
Blender version: 3.6.2
MCPrep version: 3.4.3
JDK version: 17

**Comment by mmdanggg2** [comment]
I'd guess there may be a problem with the folder you're trying to save into and it can't save the textures into the `tex` folder next to the obj. You could try saving to a different location.
