### ISSUE TITLE
Error exporting ArmorStands

### ISSUE THREAD

**Issue by neondeex** [jmc2obj/j-mc-2-obj#234]
Im having this problem exporting every single armor stand in the world!

![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/0367bc03-7ab5-4f89-bcdf-dc50c950155e)

**Comment by neondeex** [comment]
hi this is important

**Comment by mmdanggg2** [comment]
This was being caused by stands wearing elytras. Changed the code a bit so stands are more tolerant of wearing unexpected items.

**Comment by neondeex** [comment]
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/b754f452-ac0e-4aaf-8c81-b57cc0026e89)
Still getting this i have armorstands with custom heads custom ehads in tools and that type of stuff

**Comment by neondeex** [comment]
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/3a27f4a9-fd6c-4674-ad0d-e01f72ff7165)
also still getting this

**Comment by neondeex** [comment]
i have the error from 14 to 20 in the lenght latest version

**Comment by mmdanggg2** [comment]
Does this still happen with the latest [beta build](https://github.com/jmc2obj/j-mc-2-obj/suites/17637241678/artifacts/1008240028)? I've not put out a new release with those fixes yet.

**Comment by neondeex** [comment]
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/b89b4ce2-e1ce-455d-a323-4f4a49fc1951)
No errors but invisible armor stands are visible and object are not shown

**Comment by neondeex** [comment]
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/4c269d95-5154-4e4a-aa89-c1fab3c10aa1)
Custom heads no texture

**Comment by mmdanggg2** [comment]
Custom head textures should be working, I see you're in solid view, not shaded, so double check that.
Invisible armor stands should be failry simple to fix but anything other than the basic armour is not supported. While i'd like to have it, I'm probably not going to be adding that any time soon (issue for that at #223)

**Comment by neondeex** [comment]
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/3c80aec2-2724-4e0d-98bb-6b288f7ef900)
So no custom heads and custom items in hands right o heads in hads right?
do you think that will be an easy implementation so i can for the code?

**Comment by neondeex** [comment]
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/30392593/622e498e-fdb0-4e9a-bc55-5d7e7ef34a45)
Also custom heads are a little weird

**Comment by mmdanggg2** [comment]
Items will probably be quite hard to do, heads in hands may not be as hard but there is still no code to get the arm rotations so that needs to be done first for either.

The textures on the heads should look more normal once you've disabled texture filtering on them.
