### ISSUE TITLE
Installation on Blender 4.0

### ISSUE THREAD

**Issue by TheRealOscarMike** [jmc2obj/j-mc-2-obj#237]
I had this plugin back in Blender 3.6 and it since updating to 4.0 I'm not sure what I missed, but when I download the .zip I got a master folder within the zip. (I didn't unzip and blender didn't load it in as a plug in.) And this other file just downloads a .jar. I'm not exactly sure on what I'm to do with this type of file or how to use this plugin now. Point me in the right direction. Maybe I missed something, I'm gonna keep looking.

**Comment by mmdanggg2** [comment]
This is not a blender plugin, it is a standalone program. You will need to have Java installed and then just download the .jar and run it with Java.
