### ISSUE TITLE
Missing multiple different blocks for no reason?

### ISSUE THREAD

**Issue by Cartrigger** [jmc2obj/j-mc-2-obj#239]
Multiple blocks are missing and are not placed in the OBJ.

```ERROR: Couldn't find blockstate minecraft:red_candle in any resource pack!
ERROR: Couldn't find blockstate minecraft:potted_mangrove_propagule in any resource pack!
ERROR: Couldn't find blockstate minecraft:large_amethyst_bud in any resource pack!
ERROR: Couldn't find blockstate minecraft:mangrove_stairs in any resource pack!
ERROR: Couldn't find blockstate minecraft:cave_vines in any resource pack!
ERROR: Couldn't find blockstate minecraft:cave_vines_plant in any resource pack!
ERROR: Couldn't find blockstate minecraft:decorated_pot in any resource pack!
ERROR: Couldn't find blockstate minecraft:potted_azalea_bush in any resource pack!
ERROR: Couldn't find blockstate minecraft:potted_flowering_azalea_bush in any resource pack!
ERROR: Couldn't find blockstate minecraft:potted_torchflower in any resource pack!
ERROR: Couldn't find blockstate minecraft:water_cauldron in any resource pack!

**Comment by mmdanggg2** [comment]
Do you have the latest version of minecraft installed in your .minecraft directory? If you go into your settings, uncheck `Use latest minecraft version found` and then check it back on, then look in your console it should tell you what version of minecraft it has found:
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/3161587/f5256123-9ed6-4099-a689-7ab7316971a1)

**Comment by Cartrigger** [comment]
I do not use the official minecraft launcher

**Comment by mmdanggg2** [comment]
Then you need to add the minecraft .jar file, wherever your launcher saves it, as a resource pack.

**Comment by Cartrigger** [comment]
It doesn't error, but it doesn't actually have it in the model after getting the jar

**Comment by mmdanggg2** [comment]
If you enable the show debug option in the console log, what output is shown when you open and export the map?
