### ISSUE TITLE
How to export map with mod blocks?

### ISSUE THREAD

**Issue by Axon-waxby** [jmc2obj/j-mc-2-obj#240]
How to export map with mod blocks?

**Comment by mmdanggg2** [comment]
You just need to add all the mod .jar files as resource packs in the settings. Not all mods will work but if they're using the standard block model formats then it should work doing that.

**Comment by Axon-waxby** [comment]
Does it work correctly with create?

**Comment by mmdanggg2** [comment]
If they're not showing up with the mod pack added then it probably isn't going to work unfortunately.
