### ISSUE TITLE
Missing grass block below grass in 1.20.4

### ISSUE THREAD

**Issue by spacebanana420** [jmc2obj/j-mc-2-obj#242]
1.20.4 introduced some changes to how the grass and tall grass resource data work (I guess you can say it that way). The resource packs from the previous 1.20 versions do not work properly, with the grass being instead a pink block, so I switched to the 1.20.4 resource pack as I should. However, despite using the proper pack, now the top face of grass blocks below any grass instance is missing.

![image](https://github.com/jmc2obj/j-mc-2-obj/assets/98528301/52152117-f782-466d-a92a-215e839b4b55)

This is not a rendering/transparency issue, I checked. There is no geometry below the grass, creating these holes.

Steps to reproduce:
* Get the 1.20.4.jar resource pack in the default .minecraft path where jm2obj looks for, to use it in world exporting
* Export a part of your world that contains grass

**Comment by mmdanggg2** [comment]
These guys need to chill out with renaming blocks.
Fixed in 45898d33cd4ff72fc627f608a75dcd1ba769053a

**Comment by spacebanana420** [comment]
Thank you very much :+1:
