### ISSUE TITLE
Yellow stained glass panes have the beacon texture

### ISSUE THREAD

**Issue by polyzium** [jmc2obj/j-mc-2-obj#244]
![2024-03-21_00 44 48](https://github.com/jmc2obj/j-mc-2-obj/assets/22579935/6534eef0-749b-43ab-8064-75939fcadd78)
![beacon-bug](https://github.com/jmc2obj/j-mc-2-obj/assets/22579935/15259609-ec07-47fa-aa93-a4898341dceb)

**Comment by mmdanggg2** [comment]
I'm not seeing this issue, what versions and 3d app are you using?
