### ISSUE TITLE
Bug/Error during exporting entities on mc1.20.6 (jMc2Obj-124)

### ISSUE THREAD

**Issue by McCreativo** [jmc2obj/j-mc-2-obj#252]
Hello there!

I tried to export some area of my world (1.20.6), that includes entities (frames,banners, etc.) but all entities was exported wrong.
When I open the obj with the McPrep addon, all exported entities will rendered without any nbt-data, as the error shows.

![screen3](https://github.com/jmc2obj/j-mc-2-obj/assets/171799032/b9a57372-568c-47ff-a468-b2b8d755cde0)

How can that be fixed? Maybe 1.20.6 is not supported yet?

**Comment by mmdanggg2** [comment]
Entity support isn't great if I'm honest, this specific error is fixed with 08e6e3f5cbaf50a3857216c49805160747cac365
Only maps are supported in item frames for now unfortunately. Follow #223 for if this changes
