### ISSUE TITLE
Empty world, loading Minestom built world

### ISSUE THREAD

**Issue by AntonIXO** [jmc2obj/j-mc-2-obj#253]
Hi,
I am using [Minestom framework](https://github.com/Minestom/Minestom) to build my server and wanna integrate builds export.
Loading and exporting Minecraft built worlds is fine, but worlds built in Minestom server results in **null** obj and mtl files.
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/25568560/b5576220-8b9e-4020-adc0-5b2cf37dded1)

Dimension type is set to overworld. Build in center of the world. Where could be problem?

**Comment by mmdanggg2** [comment]
Does that server save in the usual anvil format? If not then it's not going to be supported. Do you have the world folder? I can take a quick look.

**Comment by AntonIXO** [comment]
> Does that server save in the usual anvil format? If not then it's not going to be supported. Do you have the world folder? I can take a quick look.

Yes, it uses Anvil, but may be something missing alongside original implementation.
Folder of simple build is pinned.
[build.zip](https://github.com/user-attachments/files/15897235/build.zip)

**Comment by mmdanggg2** [comment]
So these chunks are almost right, they're not quite consistent with what I've seen from minecraft. The worst issue is these chunks are missing the xPos and zPos tags, I can work around it but I would consider that a bug in Minestom. 

The `sections` biome tags also feature the `data` long array with a length of 1 when the whole section is just one biome as opposed to just missing as it is in minecraft, I can also account for this and I'm fine with that.

**Comment by AntonIXO** [comment]
> So these chunks are almost right, they're not quite consistent with what I've seen from minecraft. The worst issue is these chunks are missing the xPos and zPos tags, I can work around it but I would consider that a bug in Minestom.
> 
> The `sections` biome tags also feature the `data` long array with a length of 1 when the whole section is just one biome as opposed to just missing as it is in minecraft, I can also account for this and I'm fine with that.

Thanks for checking! What programs do you use to watch for tags and other data?
I'll look for zPos and zPos tags support in Minestom.
I don't understand about section tags. Does this is an issue I should fix in Minestom, or you could add workaround to jmc2obj?

**Comment by mmdanggg2** [comment]
I tend to use NBTExplorer which works even though its a bit outdated it still works. I think the sections thing is just a difference, I don't think it's a problem and I am fine to add some extra checks for that. The x and z pos tags though seem like they really should be there even if they're not absolutely critical to being able to load the chunk, The yPos tag is there but that is required for the rest of the data to make sense.
