### ISSUE TITLE
Exporting the OBJ file finishes, but stops at 100% on the GUI

### ISSUE THREAD

**Issue by ItsCre3per** [jmc2obj/j-mc-2-obj#255]
When exporting the file for a selection in the world, the GUI shows it being stuck at 100%. In the console, it shows that it is complete. The only way to export again is to restart jMC2OBJ. Not a big issue, just a confusing inconvenience.

**Comment by mmdanggg2** [comment]
I'm not seeing this issue when exporting.
I assume you mean that the export button remains greyed out? Is this with version 125 and are there any errors showing up in the console?

**Comment by ItsCre3per** [comment]
I will send an image of the problem tomorrow morning.
