### ISSUE TITLE
RE: bug while exporting entities on 1.20.6+ (jMc2Obj-125)

### ISSUE THREAD

**Issue by McCreativo** [jmc2obj/j-mc-2-obj#256]
Hello again!

I've tried to export entities on mc1.20.6 and 1.21 with the latest version (jMc2Obj-125) but still entities do render without any data.

- [ ] I reinstalled the program
- [ ] I reset my settings
- [ ] I changed my blender version to 4.1.1 (I usually use 4.3.0 alpha)
- [ ] I reset my blender settings and reinstalled mcprep v3.5.3
- [ ] I tried different mc versions 1.19, 120.4 (Its still working for older versions, all entities were exported correct)

Minecraft 1.21
![mc-orig](https://github.com/jmc2obj/j-mc-2-obj/assets/171799032/28a6b006-9631-4220-bb29-f3b03fecb65a)
Blender
![blender](https://github.com/jmc2obj/j-mc-2-obj/assets/171799032/afb68c1c-b47d-43dc-b285-e4b62cc71f36)
Export settings
![export](https://github.com/jmc2obj/j-mc-2-obj/assets/171799032/37644eab-1845-4f31-a715-44534cbb00fa)

All data was exported without any error but still when its imported into blender the same problem occurs as before...
Debug log exporting on v1.21
[bug1.21.0.txt](https://github.com/user-attachments/files/16031892/bug1.21.0.txt)
Debug log exporting on v1.20.6
[bug1.20.6.txt](https://github.com/user-attachments/files/16031893/bug1.20.6.txt)

**Comment by mmdanggg2** [comment]
These should be fixed with 7378aa5ff853fb930d7aa3b6409d3c142c26cc81 and 2491832a4f30038847d45bfb190e39e29c6ae236.
Try it out with the jar file from here: https://github.com/jmc2obj/j-mc-2-obj/actions/runs/9770710374

**Comment by McCreativo** [comment]
Hellu!

I've tested your fix https://github.com/jmc2obj/j-mc-2-obj/commit/7378aa5ff853fb930d7aa3b6409d3c142c26cc81.
Unfortunately it's not working for me entirely... Heads got still exported wrong, but this time all heads got the same texture.

Blender
![blender](https://github.com/jmc2obj/j-mc-2-obj/assets/171799032/158823e6-0877-4736-8622-9d2d973ae3c2)
Minecraft 1.21
![mc](https://github.com/jmc2obj/j-mc-2-obj/assets/171799032/8a6043af-f77a-4bd4-a3d0-0804acbba19c)

After some debugging I found the core problem. Heads that were placed by a commandblock wont be effected, but the problem occurs if I use heads that were placed by a plugin. Normally, I build my projects on my own server (fabric), I use the plugin "Headdatabase" to easily place heads in my worlds. Only these heads between the versions 1.20.4-1.20.6 are impacted.
Banners btw. are exported correct for now.

Could that be fixed? Thank you for your support!

**Comment by mmdanggg2** [comment]
Could I get a world file with these broken heads in?

**Comment by McCreativo** [comment]
> Could I get a world file with these broken heads in?

Sure! I can provide you my "test" world.
[heads-bug1.21.zip](https://github.com/user-attachments/files/16087495/heads-bug1.21.zip)

**Comment by mmdanggg2** [comment]
Ok, I see what's going on here, the plugin is setting the "name" of the texture to just "" or "HeadDatabase" when that isn't the name of the minecraft user the skin is for. Then multiple different skins are set with this same name and so any after the first it found don't get exported. Might have to ditch the nice player name for the head textures since that's clearly unreliable.

**Comment by mmdanggg2** [comment]
Addressed with 57ea682d1982878c9595d2440a6b418d52889b97
Try this one https://github.com/jmc2obj/j-mc-2-obj/actions/runs/9783782398

**Comment by McCreativo** [comment]
> Addressed with [57ea682](https://github.com/jmc2obj/j-mc-2-obj/commit/57ea682d1982878c9595d2440a6b418d52889b97) Try this one https://github.com/jmc2obj/j-mc-2-obj/actions/runs/9783782398

God bless you! It finally works! Thank you. ❤️❤️
