### ISSUE TITLE
Full Japanese translation

### ISSUE THREAD

**Issue by Takattya** [jmc2obj/j-mc-2-obj#257]
Hello. I am a Japanese user of jMc2Obj.
I have done a complete Japanese translation. (I translated all of messages.properties as is)
Until now, I have been publishing it in my personal fork repository, but I hope this will be useful for other Japanese users.
So I will share the file. I will share it as a txt file because of the extension limit.
I am still learning how to use Github. Sorry if I am wrong about anything.

[messages_ja.txt](https://github.com/user-attachments/files/16039065/messages_ja.txt)

**Comment by mmdanggg2** [comment]
Thank you for this, nice to have a proper transtlation done so fast! I've added your translation in commit b475e3ef7d714b468f8f1a88366da2de9b89e87a
お疲れ様でした！

**Comment by Takattya** [comment]
Thank you for hiring me!
However, I'm very sorry, but due to my mistake, my email address, which should have been kept private, was made public.
If possible, could you please change the email address listed in the commit to
`168965941+Takattya@users.noreply.github.com`
If that's difficult, it's fine to leave it as it is.
I'm really sorry.

**Comment by mmdanggg2** [comment]
No worries, I've updated that now with your noreply github address.
