### ISSUE TITLE
Export fine but nothing appears in Blender

### ISSUE THREAD

**Issue by User8395** [jmc2obj/j-mc-2-obj#263]
I am exporting a part of a world but when I open it in blender nothing shows up.

![image](https://github.com/user-attachments/assets/2d6c293e-4151-40c0-90c6-8677d64efc3b)

**Comment by mmdanggg2** [comment]
Are you sure it's not just far from the origin?
Try zooming to selected:
![image](https://github.com/user-attachments/assets/74c1e2f8-8fc7-4b4c-a1f7-8ca9c7d12594)
Or export with the centred option in jmc.

**Comment by User8395** [comment]
I see it now it just was very far from the origin
