### ISSUE TITLE
Holes under items on grass blocks

### ISSUE THREAD

**Issue by zoelyons** [jmc2obj/j-mc-2-obj#266]
I get this error when loading areas that have custom items over blocks.

ERROR: Couldn't find assets/minecraft/textures/#top.png in current resource packs

 When exporting it repeatedly throws the error 

![error](https://github.com/user-attachments/assets/62a051e8-16ba-48c6-a8f8-9b49fd94856e)

In blender there are holes like this.

![holes](https://github.com/user-attachments/assets/54bc7910-9627-4951-8ec9-b2cf964054f2)

Any ideas? Thanks :)

**Comment by mmdanggg2** [comment]
Might just need to add the new blocks into a `blocks-custom.conf` file and add tell it which blocks do not occlude. Bit more info here: https://github.com/jmc2obj/j-mc-2-obj/wiki/Configuration-Files#blocksconf

**Comment by zoelyons** [comment]
> Might just need to add the new blocks into a `blocks-custom.conf` file and add tell it which blocks do not occlude. Bit more info here: https://github.com/jmc2obj/j-mc-2-obj/wiki/Configuration-Files#blocksconf

So I just tried this with every option. None makes the grass appear but then the custom block doesnt. I still get TONS of errors when exporting which makes it really hard to export.

**Comment by mmdanggg2** [comment]
`None` would be the correct option for these, if you don't specify any other options then the block should look the same as without the conf so your entries should be as simple as:
```xml
	<block id="minecraft:weathered_copper_trapdoor" name="Weathered Copper Trapdoor">
		<occlusion>none</occlusion>
	</block>
```

As for the errors, can you pate the full error log here?

**Comment by zoelyons** [comment]
> `None` would be the correct option for these, if you don't specify any other options then the block should look the same as without the conf so your entries should be as simple as:
> 
> ```
> 	<block id="minecraft:weathered_copper_trapdoor" name="Weathered Copper Trapdoor">
> 		<occlusion>none</occlusion>
> 	</block>
> ```
> 
> As for the errors, can you paste the full error log here?

Hi, so yes I've set the Wildflower for example to 'none', Here is the entire log. But instantly when viewing in the program, I can see that the block shown on that spot goes from purple representing the plant, to just green like grass, and when in blender the grass under it now renders fine but the wildflower is gone.

[Log](https://pastebin.com/uPFCnAkD)

**Comment by mmdanggg2** [comment]
So that actually looks like a bug in java, which I can't do anything about unfortunately. I think I've seen that before and managed to get around it by changing the last export location in registry so this might work to fix it:
[fixExport.zip](https://github.com/user-attachments/files/16985201/fixExport.zip)

If that doesn't work, you can try installing a different version of java, seems like fixes for it were released some months ago.

**Comment by zoelyons** [comment]
> So that actually looks like a bug in java, which I can't do anything about unfortunately. I think I've seen that before and managed to get around it by changing the last export location in registry so this might work to fix it: [fixExport.zip](https://github.com/user-attachments/files/16985201/fixExport.zip)
> 
> If that doesn't work, you can try installing a different version of java, seems like fixes for it were released some months ago.

Ok updating Java fixed it, thanks so much! I guess my only question is, is there any wildcard way for me to mark stuff from a mod to have the none applied as a wildcard instead of manually having to do every one?

**Comment by mmdanggg2** [comment]
No wildcard type thing unfortunately. I tend to write small python scripts to generate the xml when I add a lot of similar blocks.

**Comment by zoelyons** [comment]
Update: Now that those constant errors are gone by updating java, the entire thing is fixed without even adding custom block configs by checking the "Create separate object for each material button." Perhaps there's a bug somewhere then if that fixes it?

**Comment by mmdanggg2** [comment]
Yea I suppose that would stop the grass disappearing but you will find that there are a ton of extra faces generated as well. Everywhere 2 different blocks are next to eachother, underground for example, which you probably don't want.
